<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GastoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('gasto')->delete();
        
        \DB::table('gasto')->insert(array (
            0 => 
            array (
                'id_gasto' => 1,
                'fecha' => '2026-02-09',
                'num_documento' => '89538593',
                'monto' => 7900,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            1 => 
            array (
                'id_gasto' => 2,
                'fecha' => '2026-02-09',
                'num_documento' => '341503',
                'monto' => 14880,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            2 => 
            array (
                'id_gasto' => 3,
                'fecha' => '2026-02-09',
                'num_documento' => '341809',
                'monto' => 21980,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            3 => 
            array (
                'id_gasto' => 4,
                'fecha' => '2026-02-09',
                'num_documento' => '342080',
                'monto' => 21980,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            4 => 
            array (
                'id_gasto' => 5,
                'fecha' => '2026-02-09',
                'num_documento' => '96488',
                'monto' => 1300,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            5 => 
            array (
                'id_gasto' => 6,
                'fecha' => '2026-02-09',
                'num_documento' => '41010',
                'monto' => 61490,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            6 => 
            array (
                'id_gasto' => 7,
                'fecha' => '2026-02-09',
                'num_documento' => '17700342587',
                'monto' => 2590,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            7 => 
            array (
                'id_gasto' => 8,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 5137,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            8 => 
            array (
                'id_gasto' => 9,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 4979,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            9 => 
            array (
                'id_gasto' => 11,
                'fecha' => '2025-10-30',
                'num_documento' => NULL,
                'monto' => 10000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de Transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            10 => 
            array (
                'id_gasto' => 12,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 150000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de Transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            11 => 
            array (
                'id_gasto' => 13,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 80000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            12 => 
            array (
                'id_gasto' => 14,
                'fecha' => '2026-02-03',
                'num_documento' => 'RC8RR3APRA',
                'monto' => 30619,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo Airbnb',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            13 => 
            array (
                'id_gasto' => 16,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 16290,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo JustBurger',
                'detalle' => 'Alimentación',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            14 => 
            array (
                'id_gasto' => 17,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 1434,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo Uber',
                'detalle' => 'Transporte',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            15 => 
            array (
                'id_gasto' => 18,
                'fecha' => '2026-02-09',
                'num_documento' => '001021954',
                'monto' => 41470,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            16 => 
            array (
                'id_gasto' => 19,
                'fecha' => '2026-02-10',
                'num_documento' => '00',
                'monto' => 4147,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'propina',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            17 => 
            array (
                'id_gasto' => 20,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 22049,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            18 => 
            array (
                'id_gasto' => 21,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 4860,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            19 => 
            array (
                'id_gasto' => 23,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 16324,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            20 => 
            array (
                'id_gasto' => 24,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 5913,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            21 => 
            array (
                'id_gasto' => 25,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            22 => 
            array (
                'id_gasto' => 26,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            23 => 
            array (
                'id_gasto' => 27,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 6890,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            24 => 
            array (
                'id_gasto' => 28,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            25 => 
            array (
                'id_gasto' => 29,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            26 => 
            array (
                'id_gasto' => 30,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 27311,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            27 => 
            array (
                'id_gasto' => 31,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 16578,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            28 => 
            array (
                'id_gasto' => 32,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            29 => 
            array (
                'id_gasto' => 33,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            30 => 
            array (
                'id_gasto' => 34,
                'fecha' => '2026-02-11',
                'num_documento' => 'sd',
                'monto' => 2000,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'caja Chica',
                'detalle' => 'Material de oficina',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            31 => 
            array (
                'id_gasto' => 35,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 89760,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            32 => 
            array (
                'id_gasto' => 36,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 43010,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            33 => 
            array (
                'id_gasto' => 37,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 12380,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            34 => 
            array (
                'id_gasto' => 39,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 31360,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            35 => 
            array (
                'id_gasto' => 40,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 14000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            36 => 
            array (
                'id_gasto' => 41,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 38010,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            37 => 
            array (
                'id_gasto' => 42,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 70150,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            38 => 
            array (
                'id_gasto' => 45,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 1500,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            39 => 
            array (
                'id_gasto' => 46,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 700,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            40 => 
            array (
                'id_gasto' => 47,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 16260,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            41 => 
            array (
                'id_gasto' => 48,
                'fecha' => '2026-01-29',
                'num_documento' => '8001',
                'monto' => 40990,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Factura',
                'detalle' => 'Equipos de computo',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            42 => 
            array (
                'id_gasto' => 49,
                'fecha' => '2026-02-12',
                'num_documento' => '597031727049',
                'monto' => 75656,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Asado',
                'id_rendicion' => 6,
                'id_validador' => 2,
            ),
            43 => 
            array (
                'id_gasto' => 50,
                'fecha' => '2026-02-14',
                'num_documento' => '1466527',
                'monto' => 3050,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            44 => 
            array (
                'id_gasto' => 51,
                'fecha' => '2026-02-14',
                'num_documento' => '599969',
                'monto' => 2300,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            45 => 
            array (
                'id_gasto' => 52,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            46 => 
            array (
                'id_gasto' => 53,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 22997,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            47 => 
            array (
                'id_gasto' => 54,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 6990,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            48 => 
            array (
                'id_gasto' => 55,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            49 => 
            array (
                'id_gasto' => 56,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            50 => 
            array (
                'id_gasto' => 57,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 12100,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            51 => 
            array (
                'id_gasto' => 58,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 7280,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            52 => 
            array (
                'id_gasto' => 59,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            53 => 
            array (
                'id_gasto' => 60,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            54 => 
            array (
                'id_gasto' => 61,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 15100,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            55 => 
            array (
                'id_gasto' => 62,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 37446,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            56 => 
            array (
                'id_gasto' => 63,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 23494,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 8,
                'id_validador' => 2,
            ),
            57 => 
            array (
                'id_gasto' => 64,
                'fecha' => '2026-02-17',
                'num_documento' => '259895',
                'monto' => 69000,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            58 => 
            array (
                'id_gasto' => 65,
                'fecha' => '2026-02-17',
                'num_documento' => '1683256',
                'monto' => 2300,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            59 => 
            array (
                'id_gasto' => 66,
                'fecha' => '2026-01-25',
                'num_documento' => NULL,
                'monto' => 125040,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'cambio de viaje',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            60 => 
            array (
                'id_gasto' => 67,
                'fecha' => '2026-01-25',
                'num_documento' => NULL,
                'monto' => 22759,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            61 => 
            array (
                'id_gasto' => 68,
                'fecha' => '2026-01-25',
                'num_documento' => NULL,
                'monto' => 12630,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            62 => 
            array (
                'id_gasto' => 69,
                'fecha' => '2026-01-25',
                'num_documento' => NULL,
                'monto' => 53570,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            63 => 
            array (
                'id_gasto' => 72,
                'fecha' => '2026-01-26',
                'num_documento' => NULL,
                'monto' => 12300,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            64 => 
            array (
                'id_gasto' => 73,
                'fecha' => '2026-01-26',
                'num_documento' => NULL,
                'monto' => 17950,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            65 => 
            array (
                'id_gasto' => 74,
                'fecha' => '2026-01-27',
                'num_documento' => NULL,
                'monto' => 3200,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            66 => 
            array (
                'id_gasto' => 75,
                'fecha' => '2026-01-28',
                'num_documento' => NULL,
                'monto' => 7600,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            67 => 
            array (
                'id_gasto' => 76,
                'fecha' => '2026-01-28',
                'num_documento' => NULL,
                'monto' => 43910,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            68 => 
            array (
                'id_gasto' => 78,
                'fecha' => '2026-01-30',
                'num_documento' => NULL,
                'monto' => 29490,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            69 => 
            array (
                'id_gasto' => 79,
                'fecha' => '2026-01-31',
                'num_documento' => NULL,
                'monto' => 17950,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            70 => 
            array (
                'id_gasto' => 80,
                'fecha' => '2026-02-01',
                'num_documento' => NULL,
                'monto' => 20650,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            71 => 
            array (
                'id_gasto' => 81,
                'fecha' => '2026-02-02',
                'num_documento' => NULL,
                'monto' => 5200,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            72 => 
            array (
                'id_gasto' => 82,
                'fecha' => '2026-03-05',
                'num_documento' => NULL,
                'monto' => 29940,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            73 => 
            array (
                'id_gasto' => 83,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 25850,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            74 => 
            array (
                'id_gasto' => 84,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 10400,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            75 => 
            array (
                'id_gasto' => 85,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 13500,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            76 => 
            array (
                'id_gasto' => 86,
                'fecha' => '2026-02-07',
                'num_documento' => NULL,
                'monto' => 4280,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            77 => 
            array (
                'id_gasto' => 87,
                'fecha' => '2026-02-02',
                'num_documento' => NULL,
                'monto' => 19200,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 10,
                'id_validador' => 2,
            ),
            78 => 
            array (
                'id_gasto' => 88,
                'fecha' => '2026-02-22',
                'num_documento' => NULL,
                'monto' => 23395,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 9,
                'id_validador' => 2,
            ),
            79 => 
            array (
                'id_gasto' => 89,
                'fecha' => '2026-02-23',
                'num_documento' => NULL,
                'monto' => 17340,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 9,
                'id_validador' => 2,
            ),
            80 => 
            array (
                'id_gasto' => 90,
                'fecha' => '2026-02-23',
                'num_documento' => NULL,
                'monto' => 23617,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 9,
                'id_validador' => 2,
            ),
            81 => 
            array (
                'id_gasto' => 91,
                'fecha' => '2026-02-24',
                'num_documento' => NULL,
                'monto' => 2590,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 9,
                'id_validador' => 2,
            ),
            82 => 
            array (
                'id_gasto' => 92,
                'fecha' => '2026-02-24',
                'num_documento' => '99435071',
                'monto' => 4350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Estacionamiento',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            83 => 
            array (
                'id_gasto' => 93,
                'fecha' => '2026-02-24',
                'num_documento' => '620050342',
                'monto' => 1490,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            84 => 
            array (
                'id_gasto' => 94,
                'fecha' => '2026-02-24',
                'num_documento' => '620050341',
                'monto' => 18570,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            85 => 
            array (
                'id_gasto' => 95,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 3000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 7,
                'id_validador' => 2,
            ),
            86 => 
            array (
                'id_gasto' => 96,
                'fecha' => '2026-01-28',
                'num_documento' => NULL,
                'monto' => 10230,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 7,
                'id_validador' => 2,
            ),
            87 => 
            array (
                'id_gasto' => 97,
                'fecha' => '2026-02-26',
                'num_documento' => '31010',
                'monto' => 2900,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            88 => 
            array (
                'id_gasto' => 98,
                'fecha' => '2026-02-26',
                'num_documento' => NULL,
                'monto' => 14850,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 7,
                'id_validador' => 2,
            ),
            89 => 
            array (
                'id_gasto' => 99,
                'fecha' => '2026-02-26',
                'num_documento' => NULL,
                'monto' => 35600,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 7,
                'id_validador' => 2,
            ),
            90 => 
            array (
                'id_gasto' => 100,
                'fecha' => '2026-02-26',
                'num_documento' => '12345',
                'monto' => 450000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Material de taller',
                'id_rendicion' => 12,
                'id_validador' => 14,
            ),
            91 => 
            array (
                'id_gasto' => 102,
                'fecha' => '2026-02-26',
                'num_documento' => '440',
                'monto' => 127290,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            92 => 
            array (
                'id_gasto' => 103,
                'fecha' => '2026-02-27',
                'num_documento' => '140325935',
                'monto' => 8830,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 14,
                'id_validador' => 2,
            ),
            93 => 
            array (
                'id_gasto' => 105,
                'fecha' => '2026-02-24',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            94 => 
            array (
                'id_gasto' => 106,
                'fecha' => '2026-02-25',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            95 => 
            array (
                'id_gasto' => 107,
                'fecha' => '2026-02-25',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            96 => 
            array (
                'id_gasto' => 109,
                'fecha' => '2026-02-26',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            97 => 
            array (
                'id_gasto' => 110,
                'fecha' => '2026-02-26',
                'num_documento' => NULL,
                'monto' => 30000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            98 => 
            array (
                'id_gasto' => 111,
                'fecha' => '2026-02-26',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            99 => 
            array (
                'id_gasto' => 112,
                'fecha' => '2026-02-25',
                'num_documento' => NULL,
                'monto' => 2100,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            100 => 
            array (
                'id_gasto' => 113,
                'fecha' => '2026-02-27',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            101 => 
            array (
                'id_gasto' => 114,
                'fecha' => '2026-02-27',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            102 => 
            array (
                'id_gasto' => 115,
                'fecha' => '2026-02-27',
                'num_documento' => NULL,
                'monto' => 42003,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            103 => 
            array (
                'id_gasto' => 116,
                'fecha' => '2026-02-27',
                'num_documento' => NULL,
                'monto' => 29486,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 15,
                'id_validador' => 2,
            ),
            104 => 
            array (
                'id_gasto' => 117,
                'fecha' => '2026-03-02',
                'num_documento' => '32336',
                'monto' => 4860,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Estacionamiento',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            105 => 
            array (
                'id_gasto' => 118,
                'fecha' => '2026-03-02',
                'num_documento' => '20083139',
                'monto' => 10800,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            106 => 
            array (
                'id_gasto' => 119,
                'fecha' => '2026-03-02',
                'num_documento' => '32344',
                'monto' => 1890,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Estacionamiento',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
        ));
        
        
    }
}