<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GastoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('gasto')->delete();
        
        \DB::table('gasto')->insert(array (
            0 => 
            array (
                'id_gasto' => 1,
                'fecha' => '2026-02-09',
                'num_documento' => '89538593',
                'monto' => 7900,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            1 => 
            array (
                'id_gasto' => 2,
                'fecha' => '2026-02-09',
                'num_documento' => '341503',
                'monto' => 14880,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            2 => 
            array (
                'id_gasto' => 3,
                'fecha' => '2026-02-09',
                'num_documento' => '341809',
                'monto' => 21980,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            3 => 
            array (
                'id_gasto' => 4,
                'fecha' => '2026-02-09',
                'num_documento' => '342080',
                'monto' => 21980,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            4 => 
            array (
                'id_gasto' => 5,
                'fecha' => '2026-02-09',
                'num_documento' => '96488',
                'monto' => 1300,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            5 => 
            array (
                'id_gasto' => 6,
                'fecha' => '2026-02-09',
                'num_documento' => '41010',
                'monto' => 61490,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            6 => 
            array (
                'id_gasto' => 7,
                'fecha' => '2026-02-09',
                'num_documento' => '17700342587',
                'monto' => 2590,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            7 => 
            array (
                'id_gasto' => 8,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 5137,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            8 => 
            array (
                'id_gasto' => 9,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 4979,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 1,
                'id_validador' => 2,
            ),
            9 => 
            array (
                'id_gasto' => 11,
                'fecha' => '2025-10-30',
                'num_documento' => NULL,
                'monto' => 10000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de Transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            10 => 
            array (
                'id_gasto' => 12,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 150000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de Transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            11 => 
            array (
                'id_gasto' => 13,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 80000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Comprobante de transferencia',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            12 => 
            array (
                'id_gasto' => 14,
                'fecha' => '2026-02-03',
                'num_documento' => 'RC8RR3APRA',
                'monto' => 30619,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo Airbnb',
                'detalle' => 'Alojamiento',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            13 => 
            array (
                'id_gasto' => 16,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 16290,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo JustBurger',
                'detalle' => 'Alimentación',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            14 => 
            array (
                'id_gasto' => 17,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 1434,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Recibo Uber',
                'detalle' => 'Transporte',
                'id_rendicion' => 3,
                'id_validador' => 2,
            ),
            15 => 
            array (
                'id_gasto' => 18,
                'fecha' => '2026-02-09',
                'num_documento' => '001021954',
                'monto' => 41470,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            16 => 
            array (
                'id_gasto' => 19,
                'fecha' => '2026-02-10',
                'num_documento' => '00',
                'monto' => 4147,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'propina',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            17 => 
            array (
                'id_gasto' => 20,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 22049,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            18 => 
            array (
                'id_gasto' => 21,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 4860,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            19 => 
            array (
                'id_gasto' => 23,
                'fecha' => '2026-02-08',
                'num_documento' => NULL,
                'monto' => 16324,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            20 => 
            array (
                'id_gasto' => 24,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 5913,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            21 => 
            array (
                'id_gasto' => 25,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            22 => 
            array (
                'id_gasto' => 26,
                'fecha' => '2026-02-09',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            23 => 
            array (
                'id_gasto' => 27,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 6890,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            24 => 
            array (
                'id_gasto' => 28,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            25 => 
            array (
                'id_gasto' => 29,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            26 => 
            array (
                'id_gasto' => 30,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 27311,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            27 => 
            array (
                'id_gasto' => 31,
                'fecha' => '2026-02-10',
                'num_documento' => NULL,
                'monto' => 16578,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            28 => 
            array (
                'id_gasto' => 32,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            29 => 
            array (
                'id_gasto' => 33,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 5,
                'id_validador' => 2,
            ),
            30 => 
            array (
                'id_gasto' => 34,
                'fecha' => '2026-02-11',
                'num_documento' => 'sd',
                'monto' => 2000,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'caja Chica',
                'detalle' => 'Material de oficina',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            31 => 
            array (
                'id_gasto' => 35,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 89760,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            32 => 
            array (
                'id_gasto' => 36,
                'fecha' => '2026-02-03',
                'num_documento' => NULL,
                'monto' => 43010,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            33 => 
            array (
                'id_gasto' => 37,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 12380,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            34 => 
            array (
                'id_gasto' => 39,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 31360,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            35 => 
            array (
                'id_gasto' => 40,
                'fecha' => '2026-02-04',
                'num_documento' => NULL,
                'monto' => 14000,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            36 => 
            array (
                'id_gasto' => 41,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 38010,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            37 => 
            array (
                'id_gasto' => 42,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 70150,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            38 => 
            array (
                'id_gasto' => 45,
                'fecha' => '2026-02-05',
                'num_documento' => NULL,
                'monto' => 1500,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            39 => 
            array (
                'id_gasto' => 46,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 700,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            40 => 
            array (
                'id_gasto' => 47,
                'fecha' => '2026-02-06',
                'num_documento' => NULL,
                'monto' => 16260,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            41 => 
            array (
                'id_gasto' => 48,
                'fecha' => '2026-01-29',
                'num_documento' => '8001',
                'monto' => 40990,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Factura',
                'detalle' => 'Equipos de computo',
                'id_rendicion' => 2,
                'id_validador' => 2,
            ),
            42 => 
            array (
                'id_gasto' => 49,
                'fecha' => '2026-02-12',
                'num_documento' => '597031727049',
                'monto' => 75656,
                'estado_gasto' => 'Aprobado',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Asado',
                'id_rendicion' => 6,
                'id_validador' => 2,
            ),
            43 => 
            array (
                'id_gasto' => 50,
                'fecha' => '2026-02-14',
                'num_documento' => '1466527',
                'monto' => 3050,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            44 => 
            array (
                'id_gasto' => 51,
                'fecha' => '2026-02-14',
                'num_documento' => '599969',
                'monto' => 2300,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Ticket',
                'detalle' => 'Peaje',
                'id_rendicion' => 4,
                'id_validador' => NULL,
            ),
            45 => 
            array (
                'id_gasto' => 52,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            46 => 
            array (
                'id_gasto' => 53,
                'fecha' => '2026-02-11',
                'num_documento' => NULL,
                'monto' => 22997,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            47 => 
            array (
                'id_gasto' => 54,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 6990,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            48 => 
            array (
                'id_gasto' => 55,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            49 => 
            array (
                'id_gasto' => 56,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            50 => 
            array (
                'id_gasto' => 57,
                'fecha' => '2026-02-12',
                'num_documento' => NULL,
                'monto' => 12100,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            51 => 
            array (
                'id_gasto' => 58,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 7280,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            52 => 
            array (
                'id_gasto' => 59,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            53 => 
            array (
                'id_gasto' => 60,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 3350,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Peaje',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            54 => 
            array (
                'id_gasto' => 61,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 15100,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Alimentación',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            55 => 
            array (
                'id_gasto' => 62,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 37446,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Combustible',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
            56 => 
            array (
                'id_gasto' => 63,
                'fecha' => '2026-02-13',
                'num_documento' => NULL,
                'monto' => 23494,
                'estado_gasto' => 'Pendiente',
                'comentario_validador' => NULL,
                'tipo_documento' => 'Boleta',
                'detalle' => 'Transporte',
                'id_rendicion' => 8,
                'id_validador' => NULL,
            ),
        ));
        
        
    }
}