<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HojasTiempoActividadesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hojas_tiempo_actividades')->delete();
        
        \DB::table('hojas_tiempo_actividades')->insert(array (
            0 => 
            array (
                'id_actividad' => 9,
                'id_hoja_diaria' => 51,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:50:00',
                'descripcion' => 'Espera habilitación de ingreso a Softys Talagante.',
                'horas_habiles' => 1.8,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 15:56:40',
                'updated_at' => '2026-03-23 15:56:40',
            ),
            1 => 
            array (
                'id_actividad' => 10,
                'id_hoja_diaria' => 51,
                'hora_inicio' => '10:50:00',
                'hora_fin' => '11:30:00',
                'descripcion' => 'Ingreso al area, inicio de actividades.',
                'horas_habiles' => 0.66666666666667,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 15:56:40',
                'updated_at' => '2026-03-23 15:56:40',
            ),
            2 => 
            array (
                'id_actividad' => 11,
                'id_hoja_diaria' => 51,
                'hora_inicio' => '11:30:00',
                'hora_fin' => '13:45:00',
                'descripcion' => 'Verificación estado sistema 800xA y servidores.',
                'horas_habiles' => 2.3,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 15:56:40',
                'updated_at' => '2026-03-23 15:56:40',
            ),
            3 => 
            array (
                'id_actividad' => 12,
                'id_hoja_diaria' => 51,
                'hora_inicio' => '13:45:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Apagado y encendido de servidores, maquinas virtualesy estaciones de operación para mantención de sala eléctrica.',
                'horas_habiles' => 4.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 15:56:40',
                'updated_at' => '2026-03-23 15:56:40',
            ),
            4 => 
            array (
                'id_actividad' => 13,
                'id_hoja_diaria' => 52,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:00:00',
                'descripcion' => 'Inicio de trabajo, coordinación de desconexión sala electrica.',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:33:06',
                'updated_at' => '2026-03-23 17:33:06',
            ),
            5 => 
            array (
                'id_actividad' => 14,
                'id_hoja_diaria' => 52,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '10:30:00',
                'descripcion' => 'Apagado del servidor para mantenimiento de sala electrica.',
                'horas_habiles' => 0.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:33:06',
                'updated_at' => '2026-03-23 17:33:06',
            ),
            6 => 
            array (
                'id_actividad' => 15,
                'id_hoja_diaria' => 52,
                'hora_inicio' => '11:30:00',
                'hora_fin' => '13:45:00',
                'descripcion' => 'Encendido de servidores y verificación de sistema 800xA.',
                'horas_habiles' => 2.2222222222222,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:33:06',
                'updated_at' => '2026-03-23 17:33:06',
            ),
            7 => 
            array (
                'id_actividad' => 16,
                'id_hoja_diaria' => 52,
                'hora_inicio' => '10:30:00',
                'hora_fin' => '11:30:00',
                'descripcion' => 'Limpieza de estaciones de operación y periféricos.',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:33:06',
                'updated_at' => '2026-03-23 17:33:06',
            ),
            8 => 
            array (
                'id_actividad' => 17,
                'id_hoja_diaria' => 52,
                'hora_inicio' => '13:45:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Chequeo de gabinete de control e I/O, chequeo de estado del controlador en control builder y de pantallas de operación',
                'horas_habiles' => 4.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:33:06',
                'updated_at' => '2026-03-23 17:33:06',
            ),
            9 => 
            array (
                'id_actividad' => 18,
                'id_hoja_diaria' => 53,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:00:00',
                'descripcion' => 'Inicio de trabajo.
Espera de instrucciones por parte de personal de Softys.',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:37:04',
                'updated_at' => '2026-03-23 17:37:04',
            ),
            10 => 
            array (
                'id_actividad' => 19,
                'id_hoja_diaria' => 53,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Comunicación con configurador RTU y encargado Softys para mostrar en despliegue gráfico potencia acumulada.
Configuración de lógica para integración de potencia activa.',
                'horas_habiles' => 8.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-23 17:37:04',
                'updated_at' => '2026-03-23 17:37:04',
            ),
            11 => 
            array (
                'id_actividad' => 23,
                'id_hoja_diaria' => 72,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:50:00',
                'descripcion' => 'Espera habilitación de ingreso a Softys Talagante.',
                'horas_habiles' => 1.8333333333333,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:40:21',
                'updated_at' => '2026-03-24 20:40:21',
            ),
            12 => 
            array (
                'id_actividad' => 24,
                'id_hoja_diaria' => 72,
                'hora_inicio' => '10:50:00',
                'hora_fin' => '11:30:00',
                'descripcion' => 'Ingreso al area, inicio de actividades.',
                'horas_habiles' => 0.66666666666667,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:40:21',
                'updated_at' => '2026-03-24 20:40:21',
            ),
            13 => 
            array (
                'id_actividad' => 25,
                'id_hoja_diaria' => 72,
                'hora_inicio' => '11:30:00',
                'hora_fin' => '13:45:00',
                'descripcion' => 'Verificación estado sistema 800xA y servidores.',
                'horas_habiles' => 2.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:40:21',
                'updated_at' => '2026-03-24 20:40:21',
            ),
            14 => 
            array (
                'id_actividad' => 26,
                'id_hoja_diaria' => 72,
                'hora_inicio' => '13:45:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Apagado y encendido de servidores, maquinas virtualesy estaciones de
operación para mantención de sala eléctrica.',
                'horas_habiles' => 4.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:40:21',
                'updated_at' => '2026-03-24 20:40:21',
            ),
            15 => 
            array (
                'id_actividad' => 27,
                'id_hoja_diaria' => 73,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:00:00',
                'descripcion' => 'Inicio de trabajo, coordinación de desconexión sala electrica',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:44:54',
                'updated_at' => '2026-03-24 20:44:54',
            ),
            16 => 
            array (
                'id_actividad' => 28,
                'id_hoja_diaria' => 73,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '10:30:00',
                'descripcion' => 'Apagado del servidor para mantenimiento de sala electrica.',
                'horas_habiles' => 0.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:44:54',
                'updated_at' => '2026-03-24 20:44:54',
            ),
            17 => 
            array (
                'id_actividad' => 29,
                'id_hoja_diaria' => 73,
                'hora_inicio' => '10:30:00',
                'hora_fin' => '11:30:00',
                'descripcion' => 'Limpieza de estaciones de operación y periféricos.',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:44:54',
                'updated_at' => '2026-03-24 20:44:54',
            ),
            18 => 
            array (
                'id_actividad' => 30,
                'id_hoja_diaria' => 73,
                'hora_inicio' => '11:30:00',
                'hora_fin' => '13:45:00',
                'descripcion' => 'Encendido de servidores y verificación de sistema 800xA.',
                'horas_habiles' => 2.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:44:54',
                'updated_at' => '2026-03-24 20:44:54',
            ),
            19 => 
            array (
                'id_actividad' => 31,
                'id_hoja_diaria' => 73,
                'hora_inicio' => '13:45:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'hequeo de gabinete de control e I/O, chequeo de estado del controlador en
control builder y de pantallas de operación.',
                'horas_habiles' => 4.25,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:44:54',
                'updated_at' => '2026-03-24 20:44:54',
            ),
            20 => 
            array (
                'id_actividad' => 32,
                'id_hoja_diaria' => 74,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '10:00:00',
                'descripcion' => 'Inicio de trabajo.
Espera de instrucciones por parte de personal de Softys.',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:45:59',
                'updated_at' => '2026-03-24 20:45:59',
            ),
            21 => 
            array (
                'id_actividad' => 33,
                'id_hoja_diaria' => 74,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Comunicación con configurador RTU y encargado Softys para mostrar en
despliegue gráfico potencia acumulada.
Configuración de lógica para integración de potencia activa.',
                'horas_habiles' => 8.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-03-24 20:45:59',
                'updated_at' => '2026-03-24 20:45:59',
            ),
            22 => 
            array (
                'id_actividad' => 34,
                'id_hoja_diaria' => 79,
                'hora_inicio' => '15:00:00',
                'hora_fin' => '17:50:00',
                'descripcion' => 'Integracion de Señales BESS en PV PPC',
                'horas_habiles' => 2.8333333333333,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-01 15:50:27',
                'updated_at' => '2026-04-01 15:50:27',
            ),
            23 => 
            array (
                'id_actividad' => 35,
                'id_hoja_diaria' => 80,
                'hora_inicio' => '14:30:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Configuraciones en PV PCC',
                'horas_habiles' => 3.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-02 14:34:41',
                'updated_at' => '2026-04-02 14:34:41',
            ),
            24 => 
            array (
                'id_actividad' => 37,
                'id_hoja_diaria' => 81,
                'hora_inicio' => '08:30:00',
                'hora_fin' => '11:00:00',
                'descripcion' => 'Configuración de señales GPM',
                'horas_habiles' => 2.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-02 20:33:15',
                'updated_at' => '2026-04-02 20:33:15',
            ),
            25 => 
            array (
                'id_actividad' => 38,
                'id_hoja_diaria' => 81,
                'hora_inicio' => '16:00:00',
                'hora_fin' => '17:30:00',
                'descripcion' => 'Pruebas comandos desde Bess',
                'horas_habiles' => 1.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-02 20:33:15',
                'updated_at' => '2026-04-02 20:33:15',
            ),
            26 => 
            array (
                'id_actividad' => 40,
                'id_hoja_diaria' => 92,
                'hora_inicio' => '08:30:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Conexion Remota',
                'horas_habiles' => 9.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-07 13:01:16',
                'updated_at' => '2026-04-07 13:01:16',
            ),
            27 => 
            array (
                'id_actividad' => 41,
                'id_hoja_diaria' => 93,
                'hora_inicio' => '08:30:00',
                'hora_fin' => '17:00:00',
                'descripcion' => 'Conexion Remota',
                'horas_habiles' => 8.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-07 20:51:56',
                'updated_at' => '2026-04-07 20:51:56',
            ),
            28 => 
            array (
                'id_actividad' => 42,
                'id_hoja_diaria' => 94,
                'hora_inicio' => '10:50:00',
                'hora_fin' => '13:00:00',
                'descripcion' => 'Conexion remota',
                'horas_habiles' => 2.1666666666667,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-08 21:00:53',
                'updated_at' => '2026-04-08 21:00:53',
            ),
            29 => 
            array (
                'id_actividad' => 43,
                'id_hoja_diaria' => 99,
                'hora_inicio' => '08:00:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Hola',
                'horas_habiles' => 0.0,
                'horas_no_habiles' => 10.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-09 19:37:59',
                'updated_at' => '2026-04-09 19:37:59',
            ),
            30 => 
            array (
                'id_actividad' => 44,
                'id_hoja_diaria' => 95,
                'hora_inicio' => '11:25:00',
                'hora_fin' => '11:50:00',
                'descripcion' => 'conexion remota',
                'horas_habiles' => 0.0,
                'horas_no_habiles' => 0.41666666666667,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-09 21:43:20',
                'updated_at' => '2026-04-09 21:43:20',
            ),
            31 => 
            array (
                'id_actividad' => 45,
                'id_hoja_diaria' => 95,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '17:45:00',
                'descripcion' => 'Pruebas de funcionalidad',
                'horas_habiles' => 0.0,
                'horas_no_habiles' => 3.75,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-09 21:43:20',
                'updated_at' => '2026-04-09 21:43:20',
            ),
            32 => 
            array (
                'id_actividad' => 47,
                'id_hoja_diaria' => 96,
                'hora_inicio' => '09:25:00',
                'hora_fin' => '11:50:00',
                'descripcion' => 'Conexion remota',
                'horas_habiles' => 2.4166666666667,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-10 19:52:38',
                'updated_at' => '2026-04-10 19:52:38',
            ),
            33 => 
            array (
                'id_actividad' => 53,
                'id_hoja_diaria' => 108,
                'hora_inicio' => '15:00:00',
                'hora_fin' => '17:00:00',
                'descripcion' => 'Resplado y modificación despliegue',
                'horas_habiles' => 2.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 15:01:48',
                'updated_at' => '2026-04-16 15:01:48',
            ),
            34 => 
            array (
                'id_actividad' => 54,
                'id_hoja_diaria' => 109,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Programación lógica',
                'horas_habiles' => 4.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 15:01:52',
                'updated_at' => '2026-04-16 15:01:52',
            ),
            35 => 
            array (
                'id_actividad' => 55,
                'id_hoja_diaria' => 110,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '16:00:00',
                'descripcion' => 'Programación lógica',
                'horas_habiles' => 2.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 15:02:16',
                'updated_at' => '2026-04-16 15:02:16',
            ),
            36 => 
            array (
                'id_actividad' => 56,
                'id_hoja_diaria' => 110,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '13:00:00',
                'descripcion' => 'Programación lógica',
                'horas_habiles' => 3.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 15:02:16',
                'updated_at' => '2026-04-16 15:02:16',
            ),
            37 => 
            array (
                'id_actividad' => 60,
                'id_hoja_diaria' => 113,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '11:00:00',
                'descripcion' => 'Reunión con operador DCS',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:08:21',
                'updated_at' => '2026-04-16 21:08:21',
            ),
            38 => 
            array (
                'id_actividad' => 61,
                'id_hoja_diaria' => 113,
                'hora_inicio' => '11:00:00',
                'hora_fin' => '13:00:00',
                'descripcion' => 'Configuración Lógica',
                'horas_habiles' => 2.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:08:21',
                'updated_at' => '2026-04-16 21:08:21',
            ),
            39 => 
            array (
                'id_actividad' => 62,
                'id_hoja_diaria' => 113,
                'hora_inicio' => '16:30:00',
                'hora_fin' => '17:30:00',
                'descripcion' => 'configuración lógica',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:08:21',
                'updated_at' => '2026-04-16 21:08:21',
            ),
            40 => 
            array (
                'id_actividad' => 63,
                'id_hoja_diaria' => 114,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '13:00:00',
                'descripcion' => 'configuración lógica',
                'horas_habiles' => 3.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:08:31',
                'updated_at' => '2026-04-16 21:08:31',
            ),
            41 => 
            array (
                'id_actividad' => 64,
                'id_hoja_diaria' => 114,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '15:00:00',
                'descripcion' => 'modificación despliegue',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:08:31',
                'updated_at' => '2026-04-16 21:08:31',
            ),
            42 => 
            array (
                'id_actividad' => 66,
                'id_hoja_diaria' => 116,
                'hora_inicio' => '10:00:00',
                'hora_fin' => '11:00:00',
                'descripcion' => 'Reunión Revisión Logíca Proyecto',
                'horas_habiles' => 1.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:10:22',
                'updated_at' => '2026-04-16 21:10:22',
            ),
            43 => 
            array (
                'id_actividad' => 67,
                'id_hoja_diaria' => 116,
                'hora_inicio' => '11:00:00',
                'hora_fin' => '13:00:00',
                'descripcion' => 'Modificación lógica y creación AFW',
                'horas_habiles' => 2.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-16 21:10:22',
                'updated_at' => '2026-04-16 21:10:22',
            ),
            44 => 
            array (
                'id_actividad' => 69,
                'id_hoja_diaria' => 135,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '19:30:00',
                'descripcion' => 'Habilitación de configuraciones HART DTM -  pruebas de uso',
                'horas_habiles' => 5.5,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-20 20:14:24',
                'updated_at' => '2026-04-20 20:14:24',
            ),
            45 => 
            array (
                'id_actividad' => 76,
                'id_hoja_diaria' => 122,
                'hora_inicio' => '08:00:00',
                'hora_fin' => '20:00:00',
                'descripcion' => 'Tendido de cableado ethernet nuevo y retiro de cabledo ethernet antiguo en area sala de servidores, mp17 y rampa de acceso.',
                'horas_habiles' => 10.0,
                'horas_no_habiles' => 2.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-21 00:05:33',
                'updated_at' => '2026-04-21 00:05:33',
            ),
            46 => 
            array (
                'id_actividad' => 77,
                'id_hoja_diaria' => 123,
                'hora_inicio' => '08:00:00',
                'hora_fin' => '20:00:00',
                'descripcion' => 'Continuación de los trabajos de retiro y tendido de cableado en área en rampa de acceso, sala eléctrica y mp16. Ademas de comienzo de ceimoado y certificación de cableado.',
                'horas_habiles' => 9.0,
                'horas_no_habiles' => 3.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-21 00:05:52',
                'updated_at' => '2026-04-21 00:05:52',
            ),
            47 => 
            array (
                'id_actividad' => 78,
                'id_hoja_diaria' => 124,
                'hora_inicio' => '08:00:00',
                'hora_fin' => '18:00:00',
                'descripcion' => 'Termino de tendido y retiro de cabledo ethernet. Se realizó certificación de cableado pendiente, instalación de patchcord de estaciones y controladores. Ademas de ordenamiento de patchpanels en gabinete de servidores del dcs.',
                'horas_habiles' => 9.0,
                'horas_no_habiles' => 1.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-21 00:06:05',
                'updated_at' => '2026-04-21 00:06:05',
            ),
            48 => 
            array (
                'id_actividad' => 81,
                'id_hoja_diaria' => 129,
                'hora_inicio' => '08:00:00',
                'hora_fin' => '09:00:00',
                'descripcion' => 'Ingreso a planta y planificacion de tareas.',
                'horas_habiles' => 0.0,
                'horas_no_habiles' => 1.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-21 20:48:07',
                'updated_at' => '2026-04-21 20:48:07',
            ),
            49 => 
            array (
                'id_actividad' => 82,
                'id_hoja_diaria' => 129,
                'hora_inicio' => '09:00:00',
                'hora_fin' => '14:00:00',
            'descripcion' => 'Etiquetado de cables de red, desmontaje de servidores (ESXi-Antiguo, PA-QCS01, PA-ASCSDC01, ESXi-01 y ESXi-02) y desmontaje de estaciones (PA-CL01y OW02). Mantenimiento preventivo al hardware de los servidores y estaciones con productos de limpieza (limpia contacto electrico, aire comprimido, alcohol isopropilico, etc).',
                'horas_habiles' => 5.0,
                'horas_no_habiles' => 0.0,
                'horas_festivas' => 0.0,
                'created_at' => '2026-04-21 20:48:07',
                'updated_at' => '2026-04-21 20:48:07',
            ),
            50 => 
            array (
                'id_actividad' => 83,
                'id_hoja_diaria' => 129,
                'hora_inicio' => '14:00:00',
                'hora_fin' => '19:00:00',
            'descripcion' => 'Desmontaje y mantenimiento preventivo de switches (SWITCH-P0 y SWITCH-P1) con productos de limpieza (limpia contactos electricos, aire comprimido, alcohol isopropilico, etc).
Montaje de servidores, switches y estaciones en rack de comunicaciones con su correspondiente conexionado.',
            'horas_habiles' => 4.0,
            'horas_no_habiles' => 1.0,
            'horas_festivas' => 0.0,
            'created_at' => '2026-04-21 20:48:07',
            'updated_at' => '2026-04-21 20:48:07',
        ),
        51 => 
        array (
            'id_actividad' => 84,
            'id_hoja_diaria' => 143,
            'hora_inicio' => '08:00:00',
            'hora_fin' => '09:00:00',
            'descripcion' => 'Ingreso a planta y planificacion de tareas.',
            'horas_habiles' => 0.0,
            'horas_no_habiles' => 1.0,
            'horas_festivas' => 0.0,
            'created_at' => '2026-04-21 21:54:13',
            'updated_at' => '2026-04-21 21:54:13',
        ),
        52 => 
        array (
            'id_actividad' => 85,
            'id_hoja_diaria' => 143,
            'hora_inicio' => '09:00:00',
            'hora_fin' => '14:00:00',
            'descripcion' => 'Etiquetado de cables de red, desmontaje de servidores y desmontaje de estaciones. Mantenimiento preventivo al hardware de los servidores y estaciones con productos de limpieza.',
            'horas_habiles' => 5.0,
            'horas_no_habiles' => 0.0,
            'horas_festivas' => 0.0,
            'created_at' => '2026-04-21 21:54:13',
            'updated_at' => '2026-04-21 21:54:13',
        ),
        53 => 
        array (
            'id_actividad' => 86,
            'id_hoja_diaria' => 143,
            'hora_inicio' => '14:00:00',
            'hora_fin' => '19:00:00',
            'descripcion' => 'Desmontaje y mantenimineto preventivo de switches con productos de limpieza . Montaje de servidores, switches y estaciones en rack de servidores con su correspondiente conexionado.',
            'horas_habiles' => 4.0,
            'horas_no_habiles' => 1.0,
            'horas_festivas' => 0.0,
            'created_at' => '2026-04-21 21:54:13',
            'updated_at' => '2026-04-21 21:54:13',
        ),
    ));
        
        
    }
}