<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HojasTiempoDiariasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hojas_tiempo_diarias')->delete();
        
        \DB::table('hojas_tiempo_diarias')->insert(array (
            0 => 
            array (
                'id_hoja_diaria' => 50,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-16',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 2.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:01:31',
            ),
            1 => 
            array (
                'id_hoja_diaria' => 51,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-17',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:01:24',
            ),
            2 => 
            array (
                'id_hoja_diaria' => 52,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-18',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:01:55',
            ),
            3 => 
            array (
                'id_hoja_diaria' => 53,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-19',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 3.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:02:00',
            ),
            4 => 
            array (
                'id_hoja_diaria' => 54,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-20',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:02:09',
            ),
            5 => 
            array (
                'id_hoja_diaria' => 55,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-21',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:02:15',
            ),
            6 => 
            array (
                'id_hoja_diaria' => 56,
                'id_hoja_semana' => 8,
                'fecha' => '2026-03-22',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-23 15:48:29',
                'updated_at' => '2026-03-23 18:02:20',
            ),
            7 => 
            array (
                'id_hoja_diaria' => 71,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-16',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 2.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            8 => 
            array (
                'id_hoja_diaria' => 72,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-17',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            9 => 
            array (
                'id_hoja_diaria' => 73,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-18',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            10 => 
            array (
                'id_hoja_diaria' => 74,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-19',
                'lugar' => 'TERRENO',
                'area' => 'Talagante',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 4.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            11 => 
            array (
                'id_hoja_diaria' => 75,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-20',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            12 => 
            array (
                'id_hoja_diaria' => 76,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-21',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            13 => 
            array (
                'id_hoja_diaria' => 77,
                'id_hoja_semana' => 11,
                'fecha' => '2026-03-22',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 11,
                'created_at' => '2026-03-24 20:35:51',
                'updated_at' => '2026-03-25 13:54:42',
            ),
            14 => 
            array (
                'id_hoja_diaria' => 78,
                'id_hoja_semana' => 12,
                'fecha' => '2026-03-30',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 20:37:00',
            ),
            15 => 
            array (
                'id_hoja_diaria' => 79,
                'id_hoja_semana' => 12,
                'fecha' => '2026-03-31',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '15:00:00',
                'horario_fin' => '17:50:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-01 15:53:42',
            ),
            16 => 
            array (
                'id_hoja_diaria' => 80,
                'id_hoja_semana' => 12,
                'fecha' => '2026-04-01',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '14:30:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 14:37:17',
            ),
            17 => 
            array (
                'id_hoja_diaria' => 81,
                'id_hoja_semana' => 12,
                'fecha' => '2026-04-02',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 20:34:31',
            ),
            18 => 
            array (
                'id_hoja_diaria' => 82,
                'id_hoja_semana' => 12,
                'fecha' => '2026-04-03',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 20:37:00',
            ),
            19 => 
            array (
                'id_hoja_diaria' => 83,
                'id_hoja_semana' => 12,
                'fecha' => '2026-04-04',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 20:37:00',
            ),
            20 => 
            array (
                'id_hoja_diaria' => 84,
                'id_hoja_semana' => 12,
                'fecha' => '2026-04-05',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-01 15:48:05',
                'updated_at' => '2026-04-02 20:37:00',
            ),
            21 => 
            array (
                'id_hoja_diaria' => 92,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-06',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:30:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-07 19:05:12',
            ),
            22 => 
            array (
                'id_hoja_diaria' => 93,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-07',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:30:00',
                'horario_fin' => '17:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-07 20:52:39',
            ),
            23 => 
            array (
                'id_hoja_diaria' => 94,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-08',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '10:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-08 21:02:13',
            ),
            24 => 
            array (
                'id_hoja_diaria' => 95,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-09',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-09 21:44:10',
            ),
            25 => 
            array (
                'id_hoja_diaria' => 96,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-10',
                'lugar' => 'OFICINA',
                'area' => NULL,
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-14 13:54:30',
            ),
            26 => 
            array (
                'id_hoja_diaria' => 97,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-11',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-14 13:54:30',
            ),
            27 => 
            array (
                'id_hoja_diaria' => 98,
                'id_hoja_semana' => 14,
                'fecha' => '2026-04-12',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-07 13:00:37',
                'updated_at' => '2026-04-14 13:54:30',
            ),
            28 => 
            array (
                'id_hoja_diaria' => 99,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-13',
                'lugar' => 'DESCANSO',
                'area' => 'Escondida',
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Rechazada',
                'observacion' => 'no',
                'validador_id' => 14,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:38:35',
            ),
            29 => 
            array (
                'id_hoja_diaria' => 100,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-14',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            30 => 
            array (
                'id_hoja_diaria' => 101,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-15',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            31 => 
            array (
                'id_hoja_diaria' => 102,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-16',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            32 => 
            array (
                'id_hoja_diaria' => 103,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-17',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            33 => 
            array (
                'id_hoja_diaria' => 104,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            34 => 
            array (
                'id_hoja_diaria' => 105,
                'id_hoja_semana' => 15,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-09 19:37:46',
                'updated_at' => '2026-04-09 19:37:46',
            ),
            35 => 
            array (
                'id_hoja_diaria' => 106,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-06',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            36 => 
            array (
                'id_hoja_diaria' => 107,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-07',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            37 => 
            array (
                'id_hoja_diaria' => 108,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-08',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            38 => 
            array (
                'id_hoja_diaria' => 109,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-09',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            39 => 
            array (
                'id_hoja_diaria' => 110,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-10',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            40 => 
            array (
                'id_hoja_diaria' => 111,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-11',
                'lugar' => 'DESCANSO',
                'area' => 'Pacifico',
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            41 => 
            array (
                'id_hoja_diaria' => 112,
                'id_hoja_semana' => 16,
                'fecha' => '2026-04-12',
                'lugar' => 'DESCANSO',
                'area' => 'Pacifico',
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-14 14:46:54',
                'updated_at' => '2026-04-16 15:03:27',
            ),
            42 => 
            array (
                'id_hoja_diaria' => 113,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-13',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            43 => 
            array (
                'id_hoja_diaria' => 114,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-14',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            44 => 
            array (
                'id_hoja_diaria' => 115,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-15',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            45 => 
            array (
                'id_hoja_diaria' => 116,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-16',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            46 => 
            array (
                'id_hoja_diaria' => 117,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-17',
                'lugar' => 'OFICINA',
                'area' => 'Pacifico',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            47 => 
            array (
                'id_hoja_diaria' => 118,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            48 => 
            array (
                'id_hoja_diaria' => 119,
                'id_hoja_semana' => 17,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Aprobada',
                'observacion' => NULL,
                'validador_id' => 1,
                'created_at' => '2026-04-16 20:57:43',
                'updated_at' => '2026-04-16 21:11:32',
            ),
            49 => 
            array (
                'id_hoja_diaria' => 120,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-13',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            50 => 
            array (
                'id_hoja_diaria' => 121,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-14',
                'lugar' => 'DESCANSO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            51 => 
            array (
                'id_hoja_diaria' => 122,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-15',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '08:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            52 => 
            array (
                'id_hoja_diaria' => 123,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-16',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            53 => 
            array (
                'id_hoja_diaria' => 124,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-17',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            54 => 
            array (
                'id_hoja_diaria' => 125,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            55 => 
            array (
                'id_hoja_diaria' => 126,
                'id_hoja_semana' => 18,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Enviada',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 19:22:01',
                'updated_at' => '2026-04-21 00:07:14',
            ),
            56 => 
            array (
                'id_hoja_diaria' => 127,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-13',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            57 => 
            array (
                'id_hoja_diaria' => 128,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-14',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            58 => 
            array (
                'id_hoja_diaria' => 129,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-15',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-21 20:48:07',
            ),
            59 => 
            array (
                'id_hoja_diaria' => 130,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-16',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            60 => 
            array (
                'id_hoja_diaria' => 131,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-17',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            61 => 
            array (
                'id_hoja_diaria' => 132,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            62 => 
            array (
                'id_hoja_diaria' => 133,
                'id_hoja_semana' => 19,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:08:48',
                'updated_at' => '2026-04-20 20:08:48',
            ),
            63 => 
            array (
                'id_hoja_diaria' => 134,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-13',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            64 => 
            array (
                'id_hoja_diaria' => 135,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-14',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '14:00:00',
                'horario_fin' => '19:30:00',
                'viaje_horas' => 2.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:14:24',
            ),
            65 => 
            array (
                'id_hoja_diaria' => 136,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-15',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            66 => 
            array (
                'id_hoja_diaria' => 137,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-16',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            67 => 
            array (
                'id_hoja_diaria' => 138,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-17',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            68 => 
            array (
                'id_hoja_diaria' => 139,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            69 => 
            array (
                'id_hoja_diaria' => 140,
                'id_hoja_semana' => 20,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:11:53',
                'updated_at' => '2026-04-20 20:11:53',
            ),
            70 => 
            array (
                'id_hoja_diaria' => 141,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-13',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
            71 => 
            array (
                'id_hoja_diaria' => 142,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-14',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
            72 => 
            array (
                'id_hoja_diaria' => 143,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-15',
                'lugar' => 'TERRENO',
                'area' => 'Puente Alto',
                'tipo_dia' => 'HABIL',
                'horario_inicio' => '09:00:00',
                'horario_fin' => '18:00:00',
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-21 21:54:13',
            ),
            73 => 
            array (
                'id_hoja_diaria' => 144,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-16',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
            74 => 
            array (
                'id_hoja_diaria' => 145,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-17',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
            75 => 
            array (
                'id_hoja_diaria' => 146,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-18',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
            76 => 
            array (
                'id_hoja_diaria' => 147,
                'id_hoja_semana' => 21,
                'fecha' => '2026-04-19',
                'lugar' => 'DESCANSO',
                'area' => NULL,
                'tipo_dia' => 'NO_HABIL',
                'horario_inicio' => NULL,
                'horario_fin' => NULL,
                'viaje_horas' => 0.0,
                'estado' => 'Borrador',
                'observacion' => NULL,
                'validador_id' => NULL,
                'created_at' => '2026-04-20 20:15:14',
                'updated_at' => '2026-04-20 20:15:14',
            ),
        ));
        
        
    }
}