<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RegistrosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('registros')->delete();
        
        \DB::table('registros')->insert(array (
            0 => 
            array (
                'id_registro_rendicion' => 1,
                'id_rendicion' => 1,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-09',
                'monto_pagado' => 142236,
                'nombre_original' => 'scaled_3fa5644f-97c5-40fc-b1d9-a8bd2119429f3245470489031184902.jpg',
                'nombre_fisico' => 'PAGO_1770667298.jpg',
                'ruta_relativa' => '001/pago/PAGO_1770667298.jpg',
                'peso_kb' => '1773.09',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id_registro_rendicion' => 2,
                'id_rendicion' => 3,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-11',
                'monto_pagado' => 48343,
                'nombre_original' => 'scaled_6d73ad32-2ad4-4f86-829c-88fca23c8b0f5452229335192230317.jpg',
                'nombre_fisico' => 'PAGO_1770840949.jpg',
                'ruta_relativa' => '003/pago/PAGO_1770840949.jpg',
                'peso_kb' => '1730.93',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id_registro_rendicion' => 3,
                'id_rendicion' => 3,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-11',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_3_1770840949.pdf',
                'ruta_relativa' => '003/pago/REPORTE_DETALLE_3_1770840949.pdf',
                'peso_kb' => '896.95',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id_registro_rendicion' => 4,
                'id_rendicion' => 5,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-11',
                'monto_pagado' => 119675,
                'nombre_original' => 'scaled_be54b7ea-e526-4707-87c0-f2511dc63dae8709114027323182806.jpg',
                'nombre_fisico' => 'PAGO_1770841127.jpg',
                'ruta_relativa' => '005/pago/PAGO_1770841127.jpg',
                'peso_kb' => '1162.79',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id_registro_rendicion' => 5,
                'id_rendicion' => 5,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-11',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_5_1770841127.pdf',
                'ruta_relativa' => '005/pago/REPORTE_DETALLE_5_1770841127.pdf',
                'peso_kb' => '4624.87',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id_registro_rendicion' => 6,
                'id_rendicion' => 6,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-12',
                'monto_pagado' => 75656,
                'nombre_original' => 'scaled_fab1f3d5-e38c-44b0-bba9-fb9df132603d5750551040158619503.jpg',
                'nombre_fisico' => 'PAGO_1770930139.jpg',
                'ruta_relativa' => '006/pago/PAGO_1770930139.jpg',
                'peso_kb' => '1026.64',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id_registro_rendicion' => 7,
                'id_rendicion' => 6,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-12',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_6_1770930139.pdf',
                'ruta_relativa' => '006/pago/REPORTE_DETALLE_6_1770930139.pdf',
                'peso_kb' => '558.69',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id_registro_rendicion' => 8,
                'id_rendicion' => 2,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-12',
                'monto_pagado' => 598120,
                'nombre_original' => 'scaled_b428b093-58d1-4d15-b3cc-630a3b6a153a1388836695427364730.jpg',
                'nombre_fisico' => 'PAGO_1770930161.jpg',
                'ruta_relativa' => '002/pago/PAGO_1770930161.jpg',
                'peso_kb' => '1218.36',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id_registro_rendicion' => 9,
                'id_rendicion' => 2,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-12',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_2_1770930161.pdf',
                'ruta_relativa' => '002/pago/REPORTE_DETALLE_2_1770930161.pdf',
                'peso_kb' => '3785.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id_registro_rendicion' => 10,
                'id_rendicion' => 8,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-18',
                'monto_pagado' => 142157,
                'nombre_original' => 'scaled_2b109e41-8bae-487f-801c-22525d860aea2763782454033428735.jpg',
                'nombre_fisico' => 'PAGO_1771449496.jpg',
                'ruta_relativa' => '008/pago/PAGO_1771449496.jpg',
                'peso_kb' => '987.38',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id_registro_rendicion' => 11,
                'id_rendicion' => 8,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-18',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_8_1771449496.pdf',
                'ruta_relativa' => '008/pago/REPORTE_DETALLE_8_1771449496.pdf',
                'peso_kb' => '4417.80',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id_registro_rendicion' => 12,
                'id_rendicion' => 9,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-24',
                'monto_pagado' => 66942,
                'nombre_original' => 'scaled_086690cb-ad0d-4faa-b16e-2d71a971d7d92124214614044111027.jpg',
                'nombre_fisico' => 'PAGO_1771958322.jpg',
                'ruta_relativa' => '009/pago/PAGO_1771958322.jpg',
                'peso_kb' => '1017.77',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id_registro_rendicion' => 13,
                'id_rendicion' => 9,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-24',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_9_1771958322.pdf',
                'ruta_relativa' => '009/pago/REPORTE_DETALLE_9_1771958322.pdf',
                'peso_kb' => '596.72',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id_registro_rendicion' => 14,
                'id_rendicion' => 10,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-24',
                'monto_pagado' => 475419,
                'nombre_original' => 'scaled_edb6c99c-4250-4f38-b055-e63f95a8e3c32823128656806038001.jpg',
                'nombre_fisico' => 'PAGO_1771958343.jpg',
                'ruta_relativa' => '010/pago/PAGO_1771958343.jpg',
                'peso_kb' => '816.17',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id_registro_rendicion' => 15,
                'id_rendicion' => 10,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-02-24',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_10_1771958343.pdf',
                'ruta_relativa' => '010/pago/REPORTE_DETALLE_10_1771958343.pdf',
                'peso_kb' => '8787.79',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id_registro_rendicion' => 16,
                'id_rendicion' => 12,
                'id_usuario_pagador' => 14,
                'fecha_pago' => '2026-02-26',
                'monto_pagado' => 450000,
                'nombre_original' => 'scaled_133850489909813208.jpg',
                'nombre_fisico' => 'PAGO_1772130226.jpg',
                'ruta_relativa' => '012/pago/PAGO_1772130226.jpg',
                'peso_kb' => '1198.70',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id_registro_rendicion' => 17,
                'id_rendicion' => 15,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 127039,
                'nombre_original' => 'scaled_49609627-b93c-402f-b02a-da154c280bbc8959037286955005386.jpg',
                'nombre_fisico' => 'PAGO_1772494506.jpg',
                'ruta_relativa' => '015/pago/PAGO_1772494506.jpg',
                'peso_kb' => '1867.30',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id_registro_rendicion' => 18,
                'id_rendicion' => 15,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_15_1772494506.pdf',
                'ruta_relativa' => '015/pago/REPORTE_DETALLE_15_1772494506.pdf',
                'peso_kb' => '4128.16',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id_registro_rendicion' => 19,
                'id_rendicion' => 14,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 8830,
                'nombre_original' => 'scaled_c045691a-cf6d-4a45-ae51-c7dec0acad493274178656825225551.jpg',
                'nombre_fisico' => 'PAGO_1772494531.jpg',
                'ruta_relativa' => '014/pago/PAGO_1772494531.jpg',
                'peso_kb' => '1369.73',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id_registro_rendicion' => 20,
                'id_rendicion' => 14,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_14_1772494531.pdf',
                'ruta_relativa' => '014/pago/REPORTE_DETALLE_14_1772494531.pdf',
                'peso_kb' => '620.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id_registro_rendicion' => 21,
                'id_rendicion' => 7,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 63680,
                'nombre_original' => 'scaled_443ce4ac-2c58-4b9f-9ee8-89f9c5a5046d746736248114039686.jpg',
                'nombre_fisico' => 'PAGO_1772494548.jpg',
                'ruta_relativa' => '007/pago/PAGO_1772494548.jpg',
                'peso_kb' => '1771.82',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id_registro_rendicion' => 22,
                'id_rendicion' => 7,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-02',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_7_1772494548.pdf',
                'ruta_relativa' => '007/pago/REPORTE_DETALLE_7_1772494548.pdf',
                'peso_kb' => '743.39',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id_registro_rendicion' => 23,
                'id_rendicion' => 17,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-09',
                'monto_pagado' => 307297,
                'nombre_original' => 'scaled_5b6792ab-79fb-4f58-80d9-a4357053d82f2796232372289730456.jpg',
                'nombre_fisico' => 'PAGO_1773096760.jpg',
                'ruta_relativa' => '017/pago/PAGO_1773096760.jpg',
                'peso_kb' => '1725.04',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id_registro_rendicion' => 24,
                'id_rendicion' => 17,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-09',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_17_1773096760.pdf',
                'ruta_relativa' => '017/pago/REPORTE_DETALLE_17_1773096760.pdf',
                'peso_kb' => '3577.15',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id_registro_rendicion' => 25,
                'id_rendicion' => 20,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-09',
                'monto_pagado' => 165000,
                'nombre_original' => 'scaled_b5d8b021-884f-4a2c-96c9-34bca66ac5dd4607370041409952154.jpg',
                'nombre_fisico' => 'PAGO_1773096844.jpg',
                'ruta_relativa' => '020/pago/PAGO_1773096844.jpg',
                'peso_kb' => '1183.71',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id_registro_rendicion' => 26,
                'id_rendicion' => 20,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-09',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_20_1773096844.pdf',
                'ruta_relativa' => '020/pago/REPORTE_DETALLE_20_1773096844.pdf',
                'peso_kb' => '120.20',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id_registro_rendicion' => 27,
                'id_rendicion' => 16,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-10',
                'monto_pagado' => 90334,
                'nombre_original' => 'scaled_461306f5-2e2c-48a3-b007-1ced921b3a8f8163488019269091405.jpg',
                'nombre_fisico' => 'PAGO_1773185157.jpg',
                'ruta_relativa' => '016/pago/PAGO_1773185157.jpg',
                'peso_kb' => '556.18',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id_registro_rendicion' => 28,
                'id_rendicion' => 16,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-10',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_16_1773185158.pdf',
                'ruta_relativa' => '016/pago/REPORTE_DETALLE_16_1773185158.pdf',
                'peso_kb' => '5825.95',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id_registro_rendicion' => 29,
                'id_rendicion' => 19,
                'id_usuario_pagador' => 14,
                'fecha_pago' => '2026-03-11',
                'monto_pagado' => 70373,
                'nombre_original' => 'scaled_WhatsApp Image 2026-03-11 at 16.02.55.jpeg',
                'nombre_fisico' => 'PAGO_1773256183.jpeg',
                'ruta_relativa' => '019/pago/PAGO_1773256183.jpeg',
                'peso_kb' => '53.99',
                'extension' => 'jpeg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id_registro_rendicion' => 30,
                'id_rendicion' => 22,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 572208,
                'nombre_original' => 'scaled_0291ef13-2dbf-45da-9d8a-08f17c7b49794676203297927221112.jpg',
                'nombre_fisico' => 'PAGO_1773414187.jpg',
                'ruta_relativa' => '022/pago/PAGO_1773414187.jpg',
                'peso_kb' => '372.12',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id_registro_rendicion' => 31,
                'id_rendicion' => 22,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_22_1773414188.pdf',
                'ruta_relativa' => '022/pago/REPORTE_DETALLE_22_1773414188.pdf',
                'peso_kb' => '1700.73',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id_registro_rendicion' => 32,
                'id_rendicion' => 21,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 312208,
                'nombre_original' => 'scaled_9ad70cec-8aab-4721-8428-2ae5cd662a795233857987751951818.jpg',
                'nombre_fisico' => 'PAGO_1773414268.jpg',
                'ruta_relativa' => '021/pago/PAGO_1773414268.jpg',
                'peso_kb' => '1530.76',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id_registro_rendicion' => 33,
                'id_rendicion' => 21,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_21_1773414268.pdf',
                'ruta_relativa' => '021/pago/REPORTE_DETALLE_21_1773414268.pdf',
                'peso_kb' => '3680.21',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id_registro_rendicion' => 34,
                'id_rendicion' => 23,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 125626,
                'nombre_original' => 'scaled_27d635fe-7cff-43fb-a2ab-816584bc7a21821751577170086152.jpg',
                'nombre_fisico' => 'PAGO_1773414306.jpg',
                'ruta_relativa' => '023/pago/PAGO_1773414306.jpg',
                'peso_kb' => '1741.16',
                'extension' => 'jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id_registro_rendicion' => 35,
                'id_rendicion' => 23,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-13',
                'monto_pagado' => 0,
                'nombre_original' => 'Reporte Automático Generado.pdf',
                'nombre_fisico' => 'REPORTE_DETALLE_23_1773414306.pdf',
                'ruta_relativa' => '023/pago/REPORTE_DETALLE_23_1773414306.pdf',
                'peso_kb' => '489.24',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id_registro_rendicion' => 36,
                'id_rendicion' => 24,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-27',
                'monto_pagado' => 165000,
                'nombre_original' => 'Matín, Rendicion 24, 165,000.pdf',
                'nombre_fisico' => 'PAGO_1774622070.pdf',
                'ruta_relativa' => '024/pago/PAGO_1774622070.pdf',
                'peso_kb' => '6.44',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id_registro_rendicion' => 37,
                'id_rendicion' => 26,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-27',
                'monto_pagado' => 1073458,
                'nombre_original' => 'Rubén, Rendicion 26, 1,073,458.pdf',
                'nombre_fisico' => 'PAGO_1774622093.pdf',
                'ruta_relativa' => '026/pago/PAGO_1774622093.pdf',
                'peso_kb' => '6.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id_registro_rendicion' => 38,
                'id_rendicion' => 30,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-27',
                'monto_pagado' => 331881,
                'nombre_original' => 'Patricio, 331.881.pdf',
                'nombre_fisico' => 'PAGO_1774641137.pdf',
                'ruta_relativa' => '030/pago/PAGO_1774641137.pdf',
                'peso_kb' => '6.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id_registro_rendicion' => 39,
                'id_rendicion' => 28,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-27',
                'monto_pagado' => 51200,
                'nombre_original' => 'Patricio, 51.200.pdf',
                'nombre_fisico' => 'PAGO_1774641151.pdf',
                'ruta_relativa' => '028/pago/PAGO_1774641151.pdf',
                'peso_kb' => '6.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id_registro_rendicion' => 40,
                'id_rendicion' => 29,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-03-27',
                'monto_pagado' => 154760,
                'nombre_original' => 'Felipe, 154.760.pdf',
                'nombre_fisico' => 'PAGO_1774641163.pdf',
                'ruta_relativa' => '029/pago/PAGO_1774641163.pdf',
                'peso_kb' => '6.46',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id_registro_rendicion' => 41,
                'id_rendicion' => 27,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-02',
                'monto_pagado' => 61820,
                'nombre_original' => 'Patricio, rendición 27, 61,820.pdf',
                'nombre_fisico' => 'PAGO_1775143883.pdf',
                'ruta_relativa' => '027/pago/PAGO_1775143883.pdf',
                'peso_kb' => '6.46',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id_registro_rendicion' => 42,
                'id_rendicion' => 18,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-02',
                'monto_pagado' => 293470,
                'nombre_original' => 'Patricio, rendición 18, 293,470.pdf',
                'nombre_fisico' => 'PAGO_1775143894.pdf',
                'ruta_relativa' => '018/pago/PAGO_1775143894.pdf',
                'peso_kb' => '6.46',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id_registro_rendicion' => 43,
                'id_rendicion' => 31,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-10',
                'monto_pagado' => 15250,
                'nombre_original' => 'Rendicion 31.pdf',
                'nombre_fisico' => 'PAGO_1775853901.pdf',
                'ruta_relativa' => '031/pago/PAGO_1775853901.pdf',
                'peso_kb' => '6.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id_registro_rendicion' => 44,
                'id_rendicion' => 33,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-10',
                'monto_pagado' => 63865,
                'nombre_original' => 'Rendicion 33.pdf',
                'nombre_fisico' => 'PAGO_1775853911.pdf',
                'ruta_relativa' => '033/pago/PAGO_1775853911.pdf',
                'peso_kb' => '6.45',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id_registro_rendicion' => 45,
                'id_rendicion' => 34,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-10',
                'monto_pagado' => 22880,
                'nombre_original' => 'Rendicion 34.pdf',
                'nombre_fisico' => 'PAGO_1775853920.pdf',
                'ruta_relativa' => '034/pago/PAGO_1775853920.pdf',
                'peso_kb' => '6.47',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id_registro_rendicion' => 46,
                'id_rendicion' => 35,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-10',
                'monto_pagado' => 326797,
                'nombre_original' => 'Rendicion 35.pdf',
                'nombre_fisico' => 'PAGO_1775853929.pdf',
                'ruta_relativa' => '035/pago/PAGO_1775853929.pdf',
                'peso_kb' => '6.47',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id_registro_rendicion' => 47,
                'id_rendicion' => 41,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-20',
                'monto_pagado' => 24590,
                'nombre_original' => 'Rendición 41.pdf',
                'nombre_fisico' => 'PAGO_1776703918.pdf',
                'ruta_relativa' => '041/pago/PAGO_1776703918.pdf',
                'peso_kb' => '6.47',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id_registro_rendicion' => 48,
                'id_rendicion' => 40,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-20',
                'monto_pagado' => 152100,
                'nombre_original' => 'Rendición 40.pdf',
                'nombre_fisico' => 'PAGO_1776703943.pdf',
                'ruta_relativa' => '040/pago/PAGO_1776703943.pdf',
                'peso_kb' => '6.49',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id_registro_rendicion' => 49,
                'id_rendicion' => 36,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-20',
                'monto_pagado' => 378420,
                'nombre_original' => 'Rendición 36.pdf',
                'nombre_fisico' => 'PAGO_1776703954.pdf',
                'ruta_relativa' => '036/pago/PAGO_1776703954.pdf',
                'peso_kb' => '6.49',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id_registro_rendicion' => 50,
                'id_rendicion' => 37,
                'id_usuario_pagador' => 2,
                'fecha_pago' => '2026-04-20',
                'monto_pagado' => 85241,
                'nombre_original' => 'Rendición 37.pdf',
                'nombre_fisico' => 'PAGO_1776703975.pdf',
                'ruta_relativa' => '037/pago/PAGO_1776703975.pdf',
                'peso_kb' => '6.46',
                'extension' => 'pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}