<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicioTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('servicio')->delete();
        
        \DB::table('servicio')->insert(array (
            0 => 
            array (
                'id_servicio' => 1,
                'nombre_servicio' => 'Migracion CV-006',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-001',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            1 => 
            array (
                'id_servicio' => 2,
                'nombre_servicio' => 'Migracion Logica Hidrometalurgia',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-002',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            2 => 
            array (
                'id_servicio' => 3,
                'nombre_servicio' => 'Tablero IO Remoto 318-XC-101',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-003',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 3,
            ),
            3 => 
            array (
                'id_servicio' => 4,
                'nombre_servicio' => 'Servicio DVS Fallback',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-004',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            4 => 
            array (
                'id_servicio' => 5,
                'nombre_servicio' => 'Tablero PLC 1131-PC-102',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-005',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 5,
            ),
            5 => 
            array (
                'id_servicio' => 6,
                'nombre_servicio' => 'Tablero PLC 1122.4-101 y Hardwares',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-006',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 6,
            ),
            6 => 
            array (
                'id_servicio' => 7,
                'nombre_servicio' => 'Macro Partidor Suave',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-007',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 7,
            ),
            7 => 
            array (
                'id_servicio' => 8,
                'nombre_servicio' => 'Gabinete IO Booster',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-008',
                'fecha_inicio' => '2022-05-25',
                'fecha_termino' => '2022-05-25',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 8,
            ),
            8 => 
            array (
                'id_servicio' => 9,
                'nombre_servicio' => 'Gabinete Catodos Control -IO',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-009',
                'fecha_inicio' => '2021-12-15',
                'fecha_termino' => '2022-08-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 9,
            ),
            9 => 
            array (
                'id_servicio' => 10,
                'nombre_servicio' => 'Gabinetes de Control',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-010',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 10,
            ),
            10 => 
            array (
                'id_servicio' => 12,
                'nombre_servicio' => 'Sistema Control - Enlace Truckshop',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-011',
                'fecha_inicio' => '2022-12-19',
                'fecha_termino' => '2024-05-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 11,
            ),
            11 => 
            array (
                'id_servicio' => 13,
                'nombre_servicio' => 'RIO Flotacion Colectiva',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-012',
                'fecha_inicio' => '2022-12-07',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 12,
            ),
            12 => 
            array (
                'id_servicio' => 14,
                'nombre_servicio' => 'EB12 SIAM',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-013',
                'fecha_inicio' => '2023-10-02',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 13,
            ),
            13 => 
            array (
                'id_servicio' => 15,
                'nombre_servicio' => 'Hardware',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-014',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 14,
            ),
            14 => 
            array (
                'id_servicio' => 16,
                'nombre_servicio' => 'Estandarizacion Despliegue Delta V',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-015',
                'fecha_inicio' => '2023-12-12',
                'fecha_termino' => '2024-05-27',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 15,
            ),
            15 => 
            array (
                'id_servicio' => 17,
                'nombre_servicio' => 'DDR Servicios',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-016',
                'fecha_inicio' => '2024-08-12',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 16,
            ),
            16 => 
            array (
                'id_servicio' => 18,
                'nombre_servicio' => 'DRR Hardware',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-017',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 17,
            ),
            17 => 
            array (
                'id_servicio' => 19,
                'nombre_servicio' => 'Scada Electrico',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-018',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 18,
            ),
            18 => 
            array (
                'id_servicio' => 20,
                'nombre_servicio' => 'Megablock y accesorios',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-019',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 19,
            ),
            19 => 
            array (
                'id_servicio' => 21,
                'nombre_servicio' => 'Piscina 40k',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-020',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 20,
            ),
            20 => 
            array (
                'id_servicio' => 22,
                'nombre_servicio' => 'Switch Cisco',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-021',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 21,
            ),
            21 => 
            array (
                'id_servicio' => 23,
                'nombre_servicio' => 'Jumpers',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-022',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 22,
            ),
            22 => 
            array (
                'id_servicio' => 24,
                'nombre_servicio' => 'Softys - Upgrade',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-001',
                'fecha_inicio' => '2020-07-28',
                'fecha_termino' => '2020-12-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            23 => 
            array (
                'id_servicio' => 25,
            'nombre_servicio' => 'CMPC (Softys), Contrato Paraguas',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-002',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            24 => 
            array (
                'id_servicio' => 26,
                'nombre_servicio' => 'TurboBlower',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-003',
                'fecha_inicio' => '2023-06-07',
                'fecha_termino' => '2023-12-19',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            25 => 
            array (
                'id_servicio' => 27,
                'nombre_servicio' => 'Trommel',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-004',
                'fecha_inicio' => '2023-08-23',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 4,
            ),
            26 => 
            array (
                'id_servicio' => 28,
                'nombre_servicio' => 'Chillers',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-005',
                'fecha_inicio' => '2023-08-23',
                'fecha_termino' => '2024-10-01',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 5,
            ),
            27 => 
            array (
                'id_servicio' => 29,
                'nombre_servicio' => 'Mantencion Talagante Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-006',
                'fecha_inicio' => '2023-10-30',
                'fecha_termino' => '2023-12-21',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 6,
            ),
            28 => 
            array (
                'id_servicio' => 30,
                'nombre_servicio' => 'Optimizacion Quimicos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-007',
                'fecha_inicio' => '2023-11-09',
                'fecha_termino' => '2023-12-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 7,
            ),
            29 => 
            array (
                'id_servicio' => 31,
                'nombre_servicio' => 'Apriete discos MP16 y MP17',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-008',
                'fecha_inicio' => '2023-07-26',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 8,
            ),
            30 => 
            array (
                'id_servicio' => 32,
                'nombre_servicio' => 'Consumo de Agua',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-009',
                'fecha_inicio' => '2023-11-09',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 9,
            ),
            31 => 
            array (
                'id_servicio' => 33,
                'nombre_servicio' => 'Configuaracion Chillers MP1 MP2',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-010',
                'fecha_inicio' => '2023-11-16',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 10,
            ),
            32 => 
            array (
                'id_servicio' => 34,
                'nombre_servicio' => 'CI871',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-011',
                'fecha_inicio' => '2023-08-31',
                'fecha_termino' => '2024-01-22',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 11,
            ),
            33 => 
            array (
                'id_servicio' => 35,
                'nombre_servicio' => 'TU838',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-012',
                'fecha_inicio' => '2023-09-25',
                'fecha_termino' => '2024-03-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 12,
            ),
            34 => 
            array (
                'id_servicio' => 36,
                'nombre_servicio' => 'Instalacion Memoria',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-013',
                'fecha_inicio' => '2023-02-09',
                'fecha_termino' => '2023-12-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 13,
            ),
            35 => 
            array (
                'id_servicio' => 37,
                'nombre_servicio' => 'TU838 Nuevas',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-014',
                'fecha_inicio' => '2024-03-21',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 14,
            ),
            36 => 
            array (
                'id_servicio' => 38,
                'nombre_servicio' => 'Reemplazo EO',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-015',
                'fecha_inicio' => '2024-01-12',
                'fecha_termino' => '2024-02-09',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 15,
            ),
            37 => 
            array (
                'id_servicio' => 39,
                'nombre_servicio' => 'Wyse Nuevo',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-016',
                'fecha_inicio' => '2024-02-26',
                'fecha_termino' => '2024-03-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 16,
            ),
            38 => 
            array (
                'id_servicio' => 40,
                'nombre_servicio' => 'Mantencion Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-017',
                'fecha_inicio' => '2024-03-04',
                'fecha_termino' => '2024-03-27',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 17,
            ),
            39 => 
            array (
                'id_servicio' => 41,
                'nombre_servicio' => 'Modulo S800 DNT',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-018',
                'fecha_inicio' => '2024-03-13',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 18,
            ),
            40 => 
            array (
                'id_servicio' => 42,
                'nombre_servicio' => 'Despliegue Consumos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-019',
                'fecha_inicio' => '2022-06-02',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 19,
            ),
            41 => 
            array (
                'id_servicio' => 43,
                'nombre_servicio' => 'Contador de Ciclos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-020',
                'fecha_inicio' => '2022-07-06',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 20,
            ),
            42 => 
            array (
                'id_servicio' => 44,
                'nombre_servicio' => 'Limpieza Tela MP16',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-021',
                'fecha_inicio' => '2024-03-28',
                'fecha_termino' => '2024-09-11',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 21,
            ),
            43 => 
            array (
                'id_servicio' => 45,
                'nombre_servicio' => 'Estacion de Operacion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-022',
                'fecha_inicio' => '2022-08-04',
                'fecha_termino' => '2024-01-02',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 22,
            ),
            44 => 
            array (
                'id_servicio' => 46,
                'nombre_servicio' => 'Audit Trail',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-023',
                'fecha_inicio' => '2022-12-27',
                'fecha_termino' => '2023-02-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 23,
            ),
            45 => 
            array (
                'id_servicio' => 47,
                'nombre_servicio' => 'Configuracion Audit Trail',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-024',
                'fecha_inicio' => '2024-03-30',
                'fecha_termino' => '2024-02-22',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 24,
            ),
            46 => 
            array (
                'id_servicio' => 48,
                'nombre_servicio' => 'Rejilla Autolimpiante',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-025',
                'fecha_inicio' => '2023-06-15',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 25,
            ),
            47 => 
            array (
                'id_servicio' => 49,
                'nombre_servicio' => 'Limpieza Tela MP17',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-026',
                'fecha_inicio' => '2023-11-23',
                'fecha_termino' => '2023-12-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 26,
            ),
            48 => 
            array (
                'id_servicio' => 50,
                'nombre_servicio' => 'Repuestos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-027',
                'fecha_inicio' => '2023-12-27',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 27,
            ),
            49 => 
            array (
                'id_servicio' => 51,
                'nombre_servicio' => 'Mirror',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-028',
                'fecha_inicio' => '2024-02-28',
                'fecha_termino' => '2024-03-07',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 28,
            ),
            50 => 
            array (
                'id_servicio' => 52,
                'nombre_servicio' => 'Repuestos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-029',
                'fecha_inicio' => '2024-03-05',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 29,
            ),
            51 => 
            array (
                'id_servicio' => 53,
                'nombre_servicio' => 'TU837',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-030',
                'fecha_inicio' => '2024-04-08',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 30,
            ),
            52 => 
            array (
                'id_servicio' => 54,
                'nombre_servicio' => 'CI854',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-031',
                'fecha_inicio' => '2024-05-02',
                'fecha_termino' => '2024-05-06',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 31,
            ),
            53 => 
            array (
                'id_servicio' => 55,
                'nombre_servicio' => 'Configuracion sonido Wyse',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-032',
                'fecha_inicio' => '2024-06-12',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 32,
            ),
            54 => 
            array (
                'id_servicio' => 56,
                'nombre_servicio' => 'Fanpress PRP',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-033',
                'fecha_inicio' => '2024-05-27',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 33,
            ),
            55 => 
            array (
                'id_servicio' => 57,
                'nombre_servicio' => 'Reparacion Wyse',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-034',
                'fecha_inicio' => '2024-05-28',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 34,
            ),
            56 => 
            array (
                'id_servicio' => 58,
                'nombre_servicio' => 'Habilitacion Process Panel',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-035',
                'fecha_inicio' => '2024-07-04',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 35,
            ),
            57 => 
            array (
                'id_servicio' => 59,
                'nombre_servicio' => 'Modulo S-800',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-036',
                'fecha_inicio' => '2024-07-12',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 36,
            ),
            58 => 
            array (
                'id_servicio' => 60,
                'nombre_servicio' => 'Programacion extraccion plastico',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-037',
                'fecha_inicio' => '2024-07-26',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 37,
            ),
            59 => 
            array (
                'id_servicio' => 61,
                'nombre_servicio' => 'Programacion DNT PRP',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-038',
                'fecha_inicio' => '2024-07-31',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 38,
            ),
            60 => 
            array (
                'id_servicio' => 62,
                'nombre_servicio' => 'Upgrade Sistema Hidraulico MP16',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-039',
                'fecha_inicio' => '2024-09-03',
                'fecha_termino' => '2024-09-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 39,
            ),
            61 => 
            array (
                'id_servicio' => 63,
                'nombre_servicio' => 'Mantencion DCS',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-040',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2024-09-13',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 40,
            ),
            62 => 
            array (
                'id_servicio' => 64,
                'nombre_servicio' => 'Programacion Aireadores',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-041',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 41,
            ),
            63 => 
            array (
                'id_servicio' => 65,
                'nombre_servicio' => 'Mantencion Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-042',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 42,
            ),
            64 => 
            array (
                'id_servicio' => 66,
                'nombre_servicio' => 'Programacion Gluepuld',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-043',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 43,
            ),
            65 => 
            array (
                'id_servicio' => 67,
                'nombre_servicio' => 'Cambio Ventiladores',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-044',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 44,
            ),
            66 => 
            array (
                'id_servicio' => 68,
                'nombre_servicio' => 'Licencias',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-045',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 45,
            ),
            67 => 
            array (
                'id_servicio' => 69,
                'nombre_servicio' => 'Instalacion KEPServerEx',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-046',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2025-03-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 46,
            ),
            68 => 
            array (
                'id_servicio' => 70,
                'nombre_servicio' => 'Programacion Sistema de Plasticos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-047',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 47,
            ),
            69 => 
            array (
                'id_servicio' => 71,
                'nombre_servicio' => 'Servicio Emergencia',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-048',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 48,
            ),
            70 => 
            array (
                'id_servicio' => 72,
                'nombre_servicio' => 'Habilitacion estaciones',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-049',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2025-02-13',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 49,
            ),
            71 => 
            array (
                'id_servicio' => 73,
                'nombre_servicio' => 'Control Bomba consistencia 200B',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-050',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 50,
            ),
            72 => 
            array (
                'id_servicio' => 74,
                'nombre_servicio' => 'Mantencion Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-051',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 51,
            ),
            73 => 
            array (
                'id_servicio' => 75,
                'nombre_servicio' => 'Habilitacion Valvulas',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-052',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 52,
            ),
            74 => 
            array (
                'id_servicio' => 76,
                'nombre_servicio' => 'Ticket Asistencia Remota',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-053',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Parcialmente facturado',
                'correlativo' => 53,
            ),
            75 => 
            array (
                'id_servicio' => 77,
                'nombre_servicio' => 'Reinstalacion de Estaciones',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-054',
                'fecha_inicio' => '2025-06-06',
                'fecha_termino' => '2025-06-06',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 54,
            ),
            76 => 
            array (
                'id_servicio' => 78,
                'nombre_servicio' => 'Control de Nivel Pozo',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-055',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 55,
            ),
            77 => 
            array (
                'id_servicio' => 79,
                'nombre_servicio' => 'Reemplazo Procesador MP16',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-056',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 56,
            ),
            78 => 
            array (
                'id_servicio' => 80,
                'nombre_servicio' => 'Integracion B852C y B921',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-057',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 57,
            ),
            79 => 
            array (
                'id_servicio' => 81,
                'nombre_servicio' => 'Reemplazo Procesador PRP',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-058',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 58,
            ),
            80 => 
            array (
                'id_servicio' => 82,
                'nombre_servicio' => 'Revision Servidores',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-059',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 59,
            ),
            81 => 
            array (
                'id_servicio' => 83,
                'nombre_servicio' => 'Ticket Asistencia Remota',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-060',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Parcialmente facturado',
                'correlativo' => 60,
            ),
            82 => 
            array (
                'id_servicio' => 84,
                'nombre_servicio' => 'Reemplazo Servidores',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-061',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Parcialmente facturado',
                'correlativo' => 61,
            ),
            83 => 
            array (
                'id_servicio' => 85,
                'nombre_servicio' => 'Servicio Emergencia',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-062',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 62,
            ),
            84 => 
            array (
                'id_servicio' => 86,
                'nombre_servicio' => 'Mantencion Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-063',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 63,
            ),
            85 => 
            array (
                'id_servicio' => 87,
                'nombre_servicio' => 'Programacion Variables Agua',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-064',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 64,
            ),
            86 => 
            array (
                'id_servicio' => 88,
                'nombre_servicio' => 'Levantamiento Interlocks',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-065',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 65,
            ),
            87 => 
            array (
                'id_servicio' => 89,
                'nombre_servicio' => 'Pacificos - Servicio 800xA',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-001',
                'fecha_inicio' => '2021-06-09',
                'fecha_termino' => '2023-03-21',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            88 => 
            array (
                'id_servicio' => 90,
                'nombre_servicio' => 'Laja',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-002',
                'fecha_inicio' => '2021-12-01',
                'fecha_termino' => '2021-12-16',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 2,
            ),
            89 => 
            array (
                'id_servicio' => 91,
                'nombre_servicio' => 'Mantencion Pacificos 2022',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-003',
                'fecha_inicio' => '2022-08-10',
                'fecha_termino' => '2022-11-17',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            90 => 
            array (
                'id_servicio' => 92,
                'nombre_servicio' => 'Pacifico - FITNIR',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-004',
                'fecha_inicio' => '2023-08-21',
                'fecha_termino' => '2024-02-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            91 => 
            array (
                'id_servicio' => 93,
                'nombre_servicio' => 'Mantencion Pacifico',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-005',
                'fecha_inicio' => '2023-08-24',
                'fecha_termino' => '2023-10-24',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 5,
            ),
            92 => 
            array (
                'id_servicio' => 94,
                'nombre_servicio' => 'DCS-PLC Inger',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-006',
                'fecha_inicio' => '2023-12-07',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 6,
            ),
            93 => 
            array (
                'id_servicio' => 95,
                'nombre_servicio' => 'Hardware Symphony',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-007',
                'fecha_inicio' => '2024-05-07',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 7,
            ),
            94 => 
            array (
                'id_servicio' => 96,
                'nombre_servicio' => 'Licencia S+ Gateway',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-008',
                'fecha_inicio' => '2024-10-10',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 8,
            ),
            95 => 
            array (
                'id_servicio' => 97,
                'nombre_servicio' => 'Mantencion Pacifico 2024',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-009',
                'fecha_inicio' => '2024-11-15',
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 9,
            ),
            96 => 
            array (
                'id_servicio' => 98,
                'nombre_servicio' => 'Configuracion en El DCS',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-010',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Parcialmente facturado',
                'correlativo' => 10,
            ),
            97 => 
            array (
                'id_servicio' => 99,
                'nombre_servicio' => 'Mantencion Pacifico 2025',
                'id_cliente' => 4,
                'id_area' => 1,
                'centro_costo' => '03-1-011',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 11,
            ),
            98 => 
            array (
                'id_servicio' => 100,
                'nombre_servicio' => 'Proyecto Coloso',
                'id_cliente' => 5,
                'id_area' => 1,
                'centro_costo' => '04-1-001',
                'fecha_inicio' => '2021-09-08',
                'fecha_termino' => '2022-08-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            99 => 
            array (
                'id_servicio' => 101,
                'nombre_servicio' => 'Suministros Gecom',
                'id_cliente' => 5,
                'id_area' => 1,
                'centro_costo' => '04-1-002',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            100 => 
            array (
                'id_servicio' => 102,
                'nombre_servicio' => 'Valmet, Repuestos',
                'id_cliente' => 5,
                'id_area' => 1,
                'centro_costo' => '04-1-003',
                'fecha_inicio' => '2021-04-29',
                'fecha_termino' => '2021-07-30',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            101 => 
            array (
                'id_servicio' => 103,
                'nombre_servicio' => 'Servicios Tacticos',
                'id_cliente' => 5,
                'id_area' => 1,
                'centro_costo' => '04-1-004',
                'fecha_inicio' => '2022-04-07',
                'fecha_termino' => '2024-02-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 4,
            ),
            102 => 
            array (
                'id_servicio' => 104,
                'nombre_servicio' => 'Rotopalas DGM',
                'id_cliente' => 6,
                'id_area' => 1,
                'centro_costo' => '05-1-001',
                'fecha_inicio' => '2021-05-11',
                'fecha_termino' => '2021-08-17',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            103 => 
            array (
                'id_servicio' => 105,
                'nombre_servicio' => 'Integracion Vibraciones Sauzal',
                'id_cliente' => 7,
                'id_area' => 1,
                'centro_costo' => '06-1-001',
                'fecha_inicio' => '2021-05-11',
                'fecha_termino' => '2021-09-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            104 => 
            array (
                'id_servicio' => 106,
                'nombre_servicio' => 'AC500',
                'id_cliente' => 8,
                'id_area' => 1,
                'centro_costo' => '07-1-001',
                'fecha_inicio' => '2021-07-07',
                'fecha_termino' => '2021-07-14',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            105 => 
            array (
                'id_servicio' => 107,
                'nombre_servicio' => 'Repuestos 1',
                'id_cliente' => 9,
                'id_area' => 1,
                'centro_costo' => '08-1-001',
                'fecha_inicio' => '2022-06-08',
                'fecha_termino' => '2022-06-08',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            106 => 
            array (
                'id_servicio' => 108,
                'nombre_servicio' => 'Repuestos 2',
                'id_cliente' => 9,
                'id_area' => 1,
                'centro_costo' => '08-1-002',
                'fecha_inicio' => '2022-08-26',
                'fecha_termino' => '2022-08-26',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 2,
            ),
            107 => 
            array (
                'id_servicio' => 109,
                'nombre_servicio' => 'Repuestos 3',
                'id_cliente' => 9,
                'id_area' => 1,
                'centro_costo' => '08-1-003',
                'fecha_inicio' => '2023-04-10',
                'fecha_termino' => '2022-04-10',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            108 => 
            array (
                'id_servicio' => 110,
                'nombre_servicio' => 'Repuestos 4',
                'id_cliente' => 9,
                'id_area' => 1,
                'centro_costo' => '08-1-004',
                'fecha_inicio' => '2024-02-27',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            109 => 
            array (
                'id_servicio' => 111,
                'nombre_servicio' => 'Revision Redes Pampa Camarones',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-001',
                'fecha_inicio' => '2022-04-29',
                'fecha_termino' => '2022-04-29',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            110 => 
            array (
                'id_servicio' => 112,
                'nombre_servicio' => 'Integracion Senal Potencia',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-002',
                'fecha_inicio' => '2022-11-23',
                'fecha_termino' => '2022-11-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 2,
            ),
            111 => 
            array (
                'id_servicio' => 113,
                'nombre_servicio' => 'Senal de Potencia',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-003',
                'fecha_inicio' => '2022-07-12',
                'fecha_termino' => '2022-07-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            112 => 
            array (
                'id_servicio' => 114,
                'nombre_servicio' => 'Levantamiento Los Loros',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-004',
                'fecha_inicio' => '2023-10-22',
                'fecha_termino' => '2023-11-09',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 4,
            ),
            113 => 
            array (
                'id_servicio' => 115,
                'nombre_servicio' => 'SCADA Gx Los Loros',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-005',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 5,
            ),
            114 => 
            array (
                'id_servicio' => 116,
                'nombre_servicio' => 'SD Procesadores',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-006',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 6,
            ),
            115 => 
            array (
                'id_servicio' => 117,
                'nombre_servicio' => 'Suministros Automation Builder',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-007',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 7,
            ),
            116 => 
            array (
                'id_servicio' => 118,
                'nombre_servicio' => 'Configuracion logica IEC104',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-008',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 8,
            ),
            117 => 
            array (
                'id_servicio' => 119,
                'nombre_servicio' => 'Configuracion senales IEC104',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-009',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 9,
            ),
            118 => 
            array (
                'id_servicio' => 120,
                'nombre_servicio' => 'Integracion PCC ABB',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-010',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 10,
            ),
            119 => 
            array (
                'id_servicio' => 121,
                'nombre_servicio' => 'Normalizacion Funciones del PPC',
                'id_cliente' => 10,
                'id_area' => 1,
                'centro_costo' => '09-1-011',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 11,
            ),
            120 => 
            array (
                'id_servicio' => 122,
                'nombre_servicio' => 'Migracion Baley-Catodos Area Seca',
                'id_cliente' => 11,
                'id_area' => 1,
                'centro_costo' => '10-1-001',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            121 => 
            array (
                'id_servicio' => 123,
                'nombre_servicio' => 'Hardware 1',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-001',
                'fecha_inicio' => '2022-05-30',
                'fecha_termino' => '2022-05-30',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            122 => 
            array (
                'id_servicio' => 124,
                'nombre_servicio' => 'Hardware 2',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-002',
                'fecha_inicio' => '2022-08-20',
                'fecha_termino' => '2022-08-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            123 => 
            array (
                'id_servicio' => 125,
                'nombre_servicio' => 'Hardware 3',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-003',
                'fecha_inicio' => '2023-03-31',
                'fecha_termino' => '2023-03-31',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 3,
            ),
            124 => 
            array (
                'id_servicio' => 126,
                'nombre_servicio' => 'Hardware 4',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-004',
                'fecha_inicio' => '2023-04-26',
                'fecha_termino' => '2023-04-26',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            125 => 
            array (
                'id_servicio' => 127,
                'nombre_servicio' => 'Hardware 5',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-005',
                'fecha_inicio' => '2023-04-26',
                'fecha_termino' => '2023-04-26',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 5,
            ),
            126 => 
            array (
                'id_servicio' => 128,
                'nombre_servicio' => 'Hardware 6',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-006',
                'fecha_inicio' => '2023-09-20',
                'fecha_termino' => '2023-09-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 6,
            ),
            127 => 
            array (
                'id_servicio' => 129,
                'nombre_servicio' => 'Hardware 7',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-007',
                'fecha_inicio' => '2023-11-16',
                'fecha_termino' => '2023-11-16',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 7,
            ),
            128 => 
            array (
                'id_servicio' => 130,
                'nombre_servicio' => 'Hardware 8',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-008',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 8,
            ),
            129 => 
            array (
                'id_servicio' => 131,
                'nombre_servicio' => 'Hardware 9',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-009',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 9,
            ),
            130 => 
            array (
                'id_servicio' => 132,
                'nombre_servicio' => 'Hardware 10',
                'id_cliente' => 12,
                'id_area' => 1,
                'centro_costo' => '11-1-010',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 10,
            ),
            131 => 
            array (
                'id_servicio' => 133,
                'nombre_servicio' => 'Hardware CP6610',
                'id_cliente' => 13,
                'id_area' => 1,
                'centro_costo' => '12-1-001',
                'fecha_inicio' => '2022-11-29',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            132 => 
            array (
                'id_servicio' => 134,
                'nombre_servicio' => 'Ingenieria Conceptual y Basica PCU comun Remota de CTA-CTH',
                'id_cliente' => 14,
                'id_area' => 1,
                'centro_costo' => '13-1-001',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            133 => 
            array (
                'id_servicio' => 135,
                'nombre_servicio' => 'Equipos AC500',
                'id_cliente' => 15,
                'id_area' => 1,
                'centro_costo' => '14-1-001',
                'fecha_inicio' => '2023-07-03',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            134 => 
            array (
                'id_servicio' => 136,
                'nombre_servicio' => 'Repuestos DI810',
                'id_cliente' => 16,
                'id_area' => 1,
                'centro_costo' => '15-1-001',
                'fecha_inicio' => '2023-09-08',
                'fecha_termino' => '2023-01-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            135 => 
            array (
                'id_servicio' => 137,
                'nombre_servicio' => 'Repuestos AI810',
                'id_cliente' => 16,
                'id_area' => 1,
                'centro_costo' => '15-1-002',
                'fecha_inicio' => '2024-01-17',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            136 => 
            array (
                'id_servicio' => 138,
                'nombre_servicio' => 'SB822',
                'id_cliente' => 17,
                'id_area' => 1,
                'centro_costo' => '16-1-001',
                'fecha_inicio' => '2023-10-12',
                'fecha_termino' => '2023-10-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            137 => 
            array (
                'id_servicio' => 139,
                'nombre_servicio' => 'Suministros Hardware ABB',
                'id_cliente' => 19,
                'id_area' => 1,
                'centro_costo' => '18-1-001',
                'fecha_inicio' => '2024-01-11',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            138 => 
            array (
                'id_servicio' => 140,
                'nombre_servicio' => 'Curso AC500',
                'id_cliente' => 18,
                'id_area' => 1,
                'centro_costo' => '17-1-001',
                'fecha_inicio' => '2023-11-17',
                'fecha_termino' => '2023-12-01',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            139 => 
            array (
                'id_servicio' => 141,
                'nombre_servicio' => 'Hardware ABB 251223',
                'id_cliente' => 20,
                'id_area' => 1,
                'centro_costo' => '19-1-001',
                'fecha_inicio' => '2023-10-16',
                'fecha_termino' => '2023-10-16',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            140 => 
            array (
                'id_servicio' => 142,
                'nombre_servicio' => 'Licencias',
                'id_cliente' => 20,
                'id_area' => 1,
                'centro_costo' => '19-1-002',
                'fecha_inicio' => '2024-04-03',
                'fecha_termino' => '2024-04-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 2,
            ),
            141 => 
            array (
                'id_servicio' => 143,
                'nombre_servicio' => 'Hardware ABB Bateria',
                'id_cliente' => 20,
                'id_area' => 1,
                'centro_costo' => '19-1-003',
                'fecha_inicio' => '2024-04-12',
                'fecha_termino' => '2024-04-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            142 => 
            array (
                'id_servicio' => 144,
                'nombre_servicio' => 'Licencias',
                'id_cliente' => 20,
                'id_area' => 1,
                'centro_costo' => '19-1-004',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            143 => 
            array (
                'id_servicio' => 145,
                'nombre_servicio' => 'Cables Redundancia',
                'id_cliente' => 20,
                'id_area' => 1,
                'centro_costo' => '19-1-005',
                'fecha_inicio' => '2024-10-11',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 5,
            ),
            144 => 
            array (
                'id_servicio' => 146,
                'nombre_servicio' => 'HMI PLC Cuenca Alta',
                'id_cliente' => 21,
                'id_area' => 1,
                'centro_costo' => '20-1-001',
                'fecha_inicio' => '2024-03-18',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            145 => 
            array (
                'id_servicio' => 147,
                'nombre_servicio' => 'Hardware',
                'id_cliente' => 22,
                'id_area' => 1,
                'centro_costo' => '21-1-001',
                'fecha_inicio' => '2024-04-02',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            146 => 
            array (
                'id_servicio' => 148,
                'nombre_servicio' => 'IAA interno',
                'id_cliente' => 1,
                'id_area' => 1,
                'centro_costo' => '00-1-001',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            147 => 
            array (
                'id_servicio' => 149,
                'nombre_servicio' => 'Aplicación Químicos Pulper PP3',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-066',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 66,
            ),
            148 => 
            array (
                'id_servicio' => 150,
                'nombre_servicio' => 'Levantamiento Forzados y Apoyo PEM',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-067',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 67,
            ),
            149 => 
            array (
                'id_servicio' => 151,
                'nombre_servicio' => 'Mantención Cogeneración',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-068',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 68,
            ),
        ));
        
        
    }
}