<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicioTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('servicio')->delete();
        
        \DB::table('servicio')->insert(array (
            0 => 
            array (
                'id_servicio' => 1,
                'nombre_servicio' => 'Migracion CV-006',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-001',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 1,
            ),
            1 => 
            array (
                'id_servicio' => 2,
                'nombre_servicio' => 'Migracion Logica Hidrometalurgia',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-002',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            2 => 
            array (
                'id_servicio' => 3,
                'nombre_servicio' => 'Tablero IO Remoto 318-XC-101',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-003',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 3,
            ),
            3 => 
            array (
                'id_servicio' => 4,
                'nombre_servicio' => 'Servicio DVS Fallback',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-004',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 4,
            ),
            4 => 
            array (
                'id_servicio' => 5,
                'nombre_servicio' => 'Tablero PLC 1131-PC-102',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-005',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 5,
            ),
            5 => 
            array (
                'id_servicio' => 6,
                'nombre_servicio' => 'Tablero PLC 1122.4-101 y Hardwares',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-006',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 6,
            ),
            6 => 
            array (
                'id_servicio' => 7,
                'nombre_servicio' => 'Macro Partidor Suave',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-007',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-03',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 7,
            ),
            7 => 
            array (
                'id_servicio' => 8,
                'nombre_servicio' => 'Gabinete IO Booster',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-008',
                'fecha_inicio' => '2022-05-25',
                'fecha_termino' => '2022-05-25',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 8,
            ),
            8 => 
            array (
                'id_servicio' => 9,
                'nombre_servicio' => 'Gabinete Catodos Control -IO',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-009',
                'fecha_inicio' => '2021-12-15',
                'fecha_termino' => '2022-08-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 9,
            ),
            9 => 
            array (
                'id_servicio' => 10,
                'nombre_servicio' => 'Gabinetes de Control',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-010',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 10,
            ),
            10 => 
            array (
                'id_servicio' => 12,
                'nombre_servicio' => 'Sistema Control - Enlace Truckshop',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-011',
                'fecha_inicio' => '2022-12-19',
                'fecha_termino' => '2024-05-05',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 11,
            ),
            11 => 
            array (
                'id_servicio' => 13,
                'nombre_servicio' => 'RIO Flotacion Colectiva',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-012',
                'fecha_inicio' => '2022-12-07',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 12,
            ),
            12 => 
            array (
                'id_servicio' => 14,
                'nombre_servicio' => 'EB12 SIAM',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-013',
                'fecha_inicio' => '2023-10-02',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 13,
            ),
            13 => 
            array (
                'id_servicio' => 15,
                'nombre_servicio' => 'Hardware',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-014',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 14,
            ),
            14 => 
            array (
                'id_servicio' => 16,
                'nombre_servicio' => 'Estandarizacion Despliegue Delta V',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-015',
                'fecha_inicio' => '2023-12-12',
                'fecha_termino' => '2024-05-27',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 15,
            ),
            15 => 
            array (
                'id_servicio' => 17,
                'nombre_servicio' => 'DDR Servicios',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-016',
                'fecha_inicio' => '2024-08-12',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 16,
            ),
            16 => 
            array (
                'id_servicio' => 18,
                'nombre_servicio' => 'DRR Hardware',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-017',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 17,
            ),
            17 => 
            array (
                'id_servicio' => 19,
                'nombre_servicio' => 'Scada Electrico',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-018',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 18,
            ),
            18 => 
            array (
                'id_servicio' => 20,
                'nombre_servicio' => 'Megablock y accesorios',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-019',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 19,
            ),
            19 => 
            array (
                'id_servicio' => 21,
                'nombre_servicio' => 'Piscina 40k',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-020',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 20,
            ),
            20 => 
            array (
                'id_servicio' => 22,
                'nombre_servicio' => 'Switch Cisco',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-021',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 21,
            ),
            21 => 
            array (
                'id_servicio' => 23,
                'nombre_servicio' => 'Jumpers',
                'id_cliente' => 2,
                'id_area' => 1,
                'centro_costo' => '01-1-022',
                'fecha_inicio' => NULL,
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 22,
            ),
            22 => 
            array (
                'id_servicio' => 24,
                'nombre_servicio' => 'Softys - Upgrade',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-001',
                'fecha_inicio' => '2020-07-28',
                'fecha_termino' => '2020-12-23',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 1,
            ),
            23 => 
            array (
                'id_servicio' => 25,
            'nombre_servicio' => 'CMPC (Softys), Contrato Paraguas',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-002',
                'fecha_inicio' => NULL,
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'No facturado',
                'correlativo' => 2,
            ),
            24 => 
            array (
                'id_servicio' => 26,
                'nombre_servicio' => 'TurboBlower',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-003',
                'fecha_inicio' => '2023-06-07',
                'fecha_termino' => '2023-12-19',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 3,
            ),
            25 => 
            array (
                'id_servicio' => 27,
                'nombre_servicio' => 'Trommel',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-004',
                'fecha_inicio' => '2023-08-23',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 4,
            ),
            26 => 
            array (
                'id_servicio' => 28,
                'nombre_servicio' => 'Chillers',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-005',
                'fecha_inicio' => '2023-08-23',
                'fecha_termino' => '2024-10-01',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 5,
            ),
            27 => 
            array (
                'id_servicio' => 29,
                'nombre_servicio' => 'Mantencion Talagante Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-006',
                'fecha_inicio' => '2023-10-30',
                'fecha_termino' => '2023-12-21',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 6,
            ),
            28 => 
            array (
                'id_servicio' => 30,
                'nombre_servicio' => 'Optimizacion Quimicos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-007',
                'fecha_inicio' => '2023-11-09',
                'fecha_termino' => '2023-12-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 7,
            ),
            29 => 
            array (
                'id_servicio' => 31,
                'nombre_servicio' => 'Apriete discos MP16 y MP17',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-008',
                'fecha_inicio' => '2023-07-26',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 8,
            ),
            30 => 
            array (
                'id_servicio' => 32,
                'nombre_servicio' => 'Consumo de Agua',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-009',
                'fecha_inicio' => '2023-11-09',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 9,
            ),
            31 => 
            array (
                'id_servicio' => 33,
                'nombre_servicio' => 'Configuaracion Chillers MP1 MP2',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-010',
                'fecha_inicio' => '2023-11-16',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 10,
            ),
            32 => 
            array (
                'id_servicio' => 34,
                'nombre_servicio' => 'CI871',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-011',
                'fecha_inicio' => '2023-08-31',
                'fecha_termino' => '2024-01-22',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 11,
            ),
            33 => 
            array (
                'id_servicio' => 35,
                'nombre_servicio' => 'TU838',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-012',
                'fecha_inicio' => '2023-09-25',
                'fecha_termino' => '2024-03-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 12,
            ),
            34 => 
            array (
                'id_servicio' => 36,
                'nombre_servicio' => 'Instalacion Memoria',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-013',
                'fecha_inicio' => '2023-02-09',
                'fecha_termino' => '2023-12-18',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 13,
            ),
            35 => 
            array (
                'id_servicio' => 37,
                'nombre_servicio' => 'TU838 Nuevas',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-014',
                'fecha_inicio' => '2024-03-21',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 14,
            ),
            36 => 
            array (
                'id_servicio' => 38,
                'nombre_servicio' => 'Reemplazo EO',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-015',
                'fecha_inicio' => '2024-01-12',
                'fecha_termino' => '2024-02-09',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 15,
            ),
            37 => 
            array (
                'id_servicio' => 39,
                'nombre_servicio' => 'Wyse Nuevo',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-016',
                'fecha_inicio' => '2024-02-26',
                'fecha_termino' => '2024-03-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 16,
            ),
            38 => 
            array (
                'id_servicio' => 40,
                'nombre_servicio' => 'Mantencion Cogeneracion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-017',
                'fecha_inicio' => '2024-03-04',
                'fecha_termino' => '2024-03-27',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 17,
            ),
            39 => 
            array (
                'id_servicio' => 41,
                'nombre_servicio' => 'Modulo S800 DNT',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-018',
                'fecha_inicio' => '2024-03-13',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 18,
            ),
            40 => 
            array (
                'id_servicio' => 42,
                'nombre_servicio' => 'Despliegue Consumos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-019',
                'fecha_inicio' => '2022-06-02',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 19,
            ),
            41 => 
            array (
                'id_servicio' => 43,
                'nombre_servicio' => 'Contador de Ciclos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-020',
                'fecha_inicio' => '2022-07-06',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 20,
            ),
            42 => 
            array (
                'id_servicio' => 44,
                'nombre_servicio' => 'Limpieza Tela MP16',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-021',
                'fecha_inicio' => '2024-03-28',
                'fecha_termino' => '2024-09-11',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 21,
            ),
            43 => 
            array (
                'id_servicio' => 45,
                'nombre_servicio' => 'Estacion de Operacion',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-022',
                'fecha_inicio' => '2022-08-04',
                'fecha_termino' => '2024-01-02',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 22,
            ),
            44 => 
            array (
                'id_servicio' => 46,
                'nombre_servicio' => 'Audit Trail',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-023',
                'fecha_inicio' => '2022-12-27',
                'fecha_termino' => '2023-02-20',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 23,
            ),
            45 => 
            array (
                'id_servicio' => 47,
                'nombre_servicio' => 'Configuracion Audit Trail',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-024',
                'fecha_inicio' => '2024-03-30',
                'fecha_termino' => '2024-02-22',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 24,
            ),
            46 => 
            array (
                'id_servicio' => 48,
                'nombre_servicio' => 'Rejilla Autolimpiante',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-025',
                'fecha_inicio' => '2023-06-15',
                'fecha_termino' => NULL,
                'estado_servicio' => 'Activo',
                'facturacion' => 'No facturado',
                'correlativo' => 25,
            ),
            47 => 
            array (
                'id_servicio' => 49,
                'nombre_servicio' => 'Limpieza Tela MP17',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-026',
                'fecha_inicio' => '2023-11-23',
                'fecha_termino' => '2023-12-12',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 26,
            ),
            48 => 
            array (
                'id_servicio' => 50,
                'nombre_servicio' => 'Repuestos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-027',
                'fecha_inicio' => '2023-12-27',
                'fecha_termino' => '2023-12-28',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 27,
            ),
            49 => 
            array (
                'id_servicio' => 51,
                'nombre_servicio' => 'Mirror',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-028',
                'fecha_inicio' => '2024-02-28',
                'fecha_termino' => '2024-03-07',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 28,
            ),
            50 => 
            array (
                'id_servicio' => 52,
                'nombre_servicio' => 'Repuestos',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-029',
                'fecha_inicio' => '2024-03-05',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 29,
            ),
            51 => 
            array (
                'id_servicio' => 53,
                'nombre_servicio' => 'TU837',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-030',
                'fecha_inicio' => '2024-04-08',
                'fecha_termino' => '2024-06-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 30,
            ),
            52 => 
            array (
                'id_servicio' => 54,
                'nombre_servicio' => 'CI854',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-031',
                'fecha_inicio' => '2024-05-02',
                'fecha_termino' => '2024-05-06',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 31,
            ),
            53 => 
            array (
                'id_servicio' => 55,
                'nombre_servicio' => 'Configuracion sonido Wyse',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-032',
                'fecha_inicio' => '2024-06-12',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 32,
            ),
            54 => 
            array (
                'id_servicio' => 56,
                'nombre_servicio' => 'Fanpress PRP',
                'id_cliente' => 3,
                'id_area' => 1,
                'centro_costo' => '02-1-033',
                'fecha_inicio' => '2024-05-27',
                'fecha_termino' => '2026-02-04',
                'estado_servicio' => 'Finalizado',
                'facturacion' => 'Totalmente facturado',
                'correlativo' => 33,
            ),
        ));
        
        
    }
}